//                                                                  
//                 O--------------------------O                     
//                 | SUMNERATOR REV09 NURSERY |                     
//                 O--------------------------O                     
//                                                                  
//                                                                  
// <AUTOMATIC MANIFESTATION IS ENABLED>                             
//                                                                  
//                                                                  
// <TECHNICIAN=>     SUMNER, BRIAN
// <AUTHORIZATION=>  UCDENVER
// <GESTATION=>      
// <SEQUENCE=>       SUMNERATOR REV09 SUITE
// <SEQUENCE=>       https://github.com/C5T2B7U/sumnerator_suite
//                                                                  



#include <iostream>
#include <string>
#include <fstream>
#include <cmath>
using std::cin;
using std::cout;
using std::endl;
using std::ifstream;
using std::ofstream;
using std::string;
using std::pow;


const int EMBRYOS = 1;


struct NURSERY
{
	string ID;
	string HELIX;
	string MANIFESTATION;
};


NURSERY EMBRYO_01 = 
{
	"SUMNERATOR_REV09_BUILD_NURSERY.cpp", 
	"SUMNERATOR_REV09_BUILD_NURSERY.cpp.EMBRYO", 
	"SUMNERATOR_REV09_BUILD_NURSERY.cpp", 
};


void GCAT();
void HARVEST_EMBRYO(NURSERY EMBRYO);


void MANIFEST_01(){HARVEST_EMBRYO(EMBRYO_01);}
void IMPLANT_HELIX_01(NURSERY EMBRYO=EMBRYO_01);


bool IMPLANT_HELIX()
{
 	ofstream probe;
	probe.open(EMBRYO_01.MANIFESTATION.c_str());

	if (probe.fail())
	{
		probe.close();
		return false;
	}

	probe.close();

	IMPLANT_HELIX_01(); 

	return true;
}


void MANIFEST()
{
	MANIFEST_01();

}


void VIEW_NURSERY()
{
	cout 

 		<< "   <EMBRYO_01.ID=>   " << "\"" << EMBRYO_01.ID << "\"" << endl
 		<< "   <MANIFESTATION=>  " << "\"" << EMBRYO_01.MANIFESTATION << "\"" << "\n\n"

		<< "\n";
}







int main()
{
	cout << "\n\n\n"
		<< "                         O--------------------------O\n"
		<< "                         | SUMNERATOR REV09 NURSERY |\n"
		<< "                         O--------------------------O\n\n\n"
		<< "      o-----------------------------------------------------------------o\n"
		<< "      | THIS NURSERY WILL MANIFEST THE FOLLOWING SOURCE CODE EMBRYO(S): |\n" 
		<< "      o-----------------------------------------------------------------o\n\n";

	VIEW_NURSERY();

	cout << "                          [PRESS ENTER TO CONTINUE] ";
// 	cin.get();


	cout << "\n\n\n     DO YOU WANT TO MANIFEST THE CODE EMBRYO(S) INTO THE ACTIVE DIRECTORY?\n"
		<< "                            [ENTER \'Y\' OR \'N\' NOW]  ";
// 		{
// 			char userWantsManifestation;
// 			do
// 			{
// 				cin >> userWantsManifestation;
// 				if ((userWantsManifestation == 'N') || (userWantsManifestation == 'n'))
// 				{
// 					cout << "\n\n\n         PLEASE RUN THIS NURSERY AGAIN TO MANIFEST THE CODE EMBRYO(S).\n\n\n"
// 						<< "                           [PRESS ENTER TO EXIT] ";
// 					cin.ignore();
// 					cin.get();
// 					return -1;
// 				}
// 			}
// 			while ((userWantsManifestation != 'Y') && (userWantsManifestation != 'y'));
// 		}


	cout << "\n\n\n";
	if (!IMPLANT_HELIX())
	{
		cout << "\n\n\n                WARNING!!! CANNOT IMPLANT HELIX INTO EMBRYO(S)!\n"
			<< "              PLEASE ENABLE WRITE ACCESS TO THE ACTIVE DIRECTORY\n"
			<< "          AND RUN THIS NURSERY AGAIN TO MANIFEST THE CODE EMBRYO(S).\n\n"
			<< "                           [PRESS ENTER TO EXIT]  ";
		cin.ignore();
		cin.get();
		return -11;
	}


	cout << "\n\n\n            SUCCESSFULLY IMPLANTED HELIX INTO SOURCE CODE EMBRYO(S)\n"
		<< "                    [PRESS ENTER TO MANIFEST EMBRYO(S) NOW]\n\n\n";
// 	cin.ignore();
// 	cin.get();


	cout << "           [NOW MANIFESTING THE SOURCE CODE EMBRYO(S). PLEASE WAIT.]\n\n\n";
	MANIFEST();
	cout << "\n\n\n           EMBRYO MANIFESTATION COMPLETE. PLEASE COMPILE AND RUN THE \n" 
		<< "          SOURCE CODE WHICH HAS MANIFESTED INTO THE ACTIVE DIRECTORY.\n\n\n"
		<< "                           [PRESS ENTER TO EXIT]\n\n\n";
// 	cin.get();


	return 420-420;
}





void IMPLANT_HELIX_01(NURSERY EMBRYO){ofstream HELIX(EMBRYO.HELIX.c_str());
HELIX<<"ATAAATAAGAGAATAAATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGAATAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAAATAGAGAATAAATAAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGCCTAGCGGTACGTGTGAGTAGATAAGTGCACG\n";GCAT();
HELIX<<"AGCGCGTGAATACACGGCGGCACGAGTGCATGCCGGTCGAGCGGTACGTGTGAGCA\n";GCAT();
HELIX<<"CGTGAGTGGCGGCCTAGAGAATAAATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AATAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAAATAGAGAATAA\n";GCAT();
HELIX<<"ATAAGAGAATAAATAAGCGGCCAACGTGAGTGAACGGGCAGATAAGCAAACGAGCA\n";GCAT();
HELIX<<"AGCGGATATCAACTAAGCGGGCGGGCGGGCGGGCGGTACGTGTGAGTAGATAAGTG\n";GCAT();
HELIX<<"CACGGCAAGCGGGACGCACGAGCAAGCGGATAGAGAATAAATAAGCGGCCAATACG\n";GCAT();
HELIX<<"AGTGTGCGTGTGAGTGGATAAACGAGTGTCAACTAAGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCCACCTGCCTGCCCGTTCGCTGAATAAATAAATTGACCACCTGGCCA\n";GCAT();
HELIX<<"TCTGGTCGGTAAATCGATTAACTAATAAAACGTCAGCGTGCTGGGACGTTAGTGTG\n";GCAT();
HELIX<<"ATAATTCGTCTGACTAGTTAACTGCTCGACCGCCTGATTACTCGTATATTCGTCTG\n";GCAT();
HELIX<<"ACCACCTGACTGGTAAATTGACCACCTGGAGAATAAATAAGAGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"GAGAATGGACCAGTTAATCGGCTATCTGGCTGACTGGCGGCCAAACCAATTATTCG\n";GCAT();
HELIX<<"CCTGCTCGACTGACCGACTACTAAGAGAATGGACCAGTTAATCGGCTATCTGGCTG\n";GCAT();
HELIX<<"ACTGGCGGCCAAGTTGTTCGCCTGCTCGACTGACCGACTACTAAGAGAATGGACCA\n";GCAT();
HELIX<<"GTTAATCGGCTATCTGGCTGACTGGCGGCCAATTCGCCTGCTCGACCAGTTAATTG\n";GCAT();
HELIX<<"CTAAGAGAATGGACCAGTTAATCGGCTATCTGGCTGACTGGCGGCCAAACCAATTA\n";GCAT();
HELIX<<"ACTAACCGGTTAACCACCCGCTAAGAGAATGGACCAGTTAATCGGCTATCTGGCTG\n";GCAT();
HELIX<<"ACTGGCGGCCAAGTCGACCACCTGTTCGACTGCCTGCTAAGAGAATGGACCAGTTA\n";GCAT();
HELIX<<"ATCGGCTATCTGGCTGACTGGCGGCCAAATCGATCGCCTGTCCACCCGACTGCTAA\n";GCAT();
HELIX<<"GAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGTTGAGAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGA\n";GCAT();
HELIX<<"CTGAATCGACCAGTTATTGAGAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTG\n";GCAT();
HELIX<<"GCTGCTGACTGAACTGGTTAGCTGGCTATTGAGAGATCTGTTCGACCAGTTAATTG\n";GCAT();
HELIX<<"GCGGTTCGCCTGGCTGCTGACTGAACCAGTTGTTCGCCTGCTCGACTGACCGACTA\n";GCAT();
HELIX<<"TTGAGAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGAATTA\n";GCAT();
HELIX<<"GTTGTTCGCCTGCTCGACTGACCGACTATTGAGAGATCTGTTCGACCAGTTAATTG\n";GCAT();
HELIX<<"GCGGTTCGCCTGGCTGCTGACTGATTCGCCTGCTCGACCAGTTAATTGTTGAGAGA\n";GCAT();
HELIX<<"TCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGATTCGACTGCCTG\n";GCAT();
HELIX<<"TTTGTTGAGAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGA\n";GCAT();
HELIX<<"TTCGACTGCCTGGTTGACCAGCTAGCTATTGAGAGATCTGTTCGACCAGTTAATTG\n";GCAT();
HELIX<<"GCGGTTCGCCTGGCTGCTGACTGAGTCGACCACCTGTTCGACTGCCTGTTGAGAGA\n";GCAT();
HELIX<<"TCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGACCTGATTATCTG\n";GCAT();
HELIX<<"CCCGCCCGACTGCTCGTTGAGAGAGAGAGAGAGAGACTTGATTAACCAGCTGGCGG\n";GCAT();
HELIX<<"ACTGGTTAATCGAATGAACGAGCGCGTGCCGGTTAGGCGAATTAGTTGTTCGCCTG\n";GCAT();
HELIX<<"CTCGACTGACCGACTAGCGGGTAGACTGGTTAATCGATTAGCTGACTGGCTGGCAA\n";GCAT();
HELIX<<"GCGGACCAGTTACCTGGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTA\n";GCAT();
HELIX<<"TTCGGCAAGCGGTTCGCCTGCTCGACCAGTTAATTGGCGGTTCGATTATCTGCTCG\n";GCAT();
HELIX<<"ATCGACTGACGATTGAGAGACTTGATTAACCAGCTGGCGGGTCGATTAATTACCTG\n";GCAT();
HELIX<<"TTCGCCTGCTCGACCGCCCGTATACCGGTCGGGCGAATTAGTTGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACTGACCGACTAGCGGGTAGACTAACCGATCAACTGGCAAGCGGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACCAGTTAATTGGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGACGA\n";GCAT();
HELIX<<"TTGAGAGACTTGATTAACCAGCTGGCGGGTCGATTAATTACCTGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACCGCCCGTATACCGGCTGGGCGAATTAGTTGTTCGCCTGCTCGACTGACCGACTA\n";GCAT();
HELIX<<"GCGGGTAGACTAACCGATCAACTGGCAAGCGGACCAGTTACCTGGCGGGTTATCTG\n";GCAT();
HELIX<<"ACTAAGTGACTAGTCGCTCGTCCAATTATTCGACGATTGAGAGAGAGAGAGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGACTAACCGACCAGTTAGCGAACGAGAGATTCAGAGAAGGAGAGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAACCAGTTACCTGGCGGGTTATCTGACTAAGTGACTAGTCGCTCG\n";GCAT();
HELIX<<"TCCAATTATTCGGCAAGCGGACCAGTTAGCTGACTGCCCATTGAGAGAAGGATTCG\n";GCAT();
HELIX<<"CCTGCTCGACCAGTTAATTGGCGGACTAACCGATCAACTGGATGACCAGCTAACTG\n";GCAT();
HELIX<<"GCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGTTGAGAGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAAGGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAACGTAGTTAGTGGGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGTACGTGTGAGTAGATAAGTGCACGAGCGCGTGAATACACG\n";GCAT();
HELIX<<"GCGGCACGAGTGCATGCCGGTCGAGCGGTACGTGTGAGCACGTGAGTGCGTAGTTA\n";GCAT();
HELIX<<"GTGGGAGAAGGAAGGACCAACCAAGCGGGTGGACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAACGTAGTTACGTAGTTAGTGGTTGAGAGAGAGAGAGAAGGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGGCGGCCAACCAAGCGGGTGGAGTGGATACGTGAGTGCACGGCGGGATG\n";GCAT();
HELIX<<"AGCAGGTAAGTGGCGGGATAAGCGAGTAAGTGGCGGCGTGAATAGCGGGACGTGTG\n";GCAT();
HELIX<<"AGCAGGTAGGTGCTAAGCGGGCGGGTGGTTGAGAGAAGGAATTGACTGCCTGGCTA\n";GCAT();
HELIX<<"ACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGACTAACCGATCAACTGGATG\n";GCAT();
HELIX<<"ACCAGCTAACTGACGATTGAGAGAGAGAGAGAAGGAACCAGTTGGCGGGCGAACTA\n";GCAT();
HELIX<<"ACCGATCAACTGGATGACCAGCTAACTGGTAAGCTAACTGGTTAATTGCCTGGCCA\n";GCAT();
HELIX<<"GCGAACGAGCGGCTAAGCGGCCAGACGAGAGAAGGATTCAGAGAAGGAAGGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGGCTAACTGGTTAATTGCCTGGCCAGCGGTCAAGCGGACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGATGACCAGCTAACTGGTAAGCTAACTGGTTAATTGCCTGGCCAGCGA\n";GCAT();
HELIX<<"ACGATTGAGAGAGAGAAGGAAGGAACCAGTTGGCGGGCGAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"ACTAACCGATCAACTGGATGACCAGCTAACTGTACAGCTAACTGGTTAATTGCCTG\n";GCAT();
HELIX<<"GCCAACAACCAGTGTAGCGGTCAATCAAGCGGATAGGTAAATAGGCGGGTAGGTAG\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGACCTGATTATCTGCCCGCCCGACTGCTCGGCGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGATGACCAGCTAACTGTACAGCTAACTGGTTAATTGCCTGGCCAACAA\n";GCAT();
HELIX<<"TTGGTGTAACGAGCGGTCAATCAAGCGGATAGAACGATAGGCGGGTAGGTAGGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCTGATTATCTGCCCGCCCGACTGCTCGGCGAACTAACCGATCA\n";GCAT();
HELIX<<"ACTGGATGACCAGCTAACTGTACAGCTAACTGGTTAATTGCCTGGCCAACAACTGG\n";GCAT();
HELIX<<"TGTAACGAGCGGTCAATCAAGCGGATAGCGCGATAGGCGGGTAGGTAGGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGACCTGATTATCTGCCCGCCCGACTGCTCGGCGAACTAACCGATCAACTG\n";GCAT();
HELIX<<"GATGACCAGCTAACTGTACAGCTAACTGGTTAATTGCCTGGCCAACAATCGGTGTA\n";GCAT();
HELIX<<"ACGAGCGGTCAATCAAGCGGATAGCGCGATAGGAGAAGGAAGGAAGGAACGAGAGA\n";GCAT();
HELIX<<"AGGAAGGATTCAGAGAAGGAAGGAAGGAATAAATAAGCGGGGTGAATAGCGGGATA\n";GCAT();
HELIX<<"AATACGTGGGCAAGCAGATAAATGGAGAAGGAAGGATCTAGAGAAGGAAGGAACTG\n";GCAT();
HELIX<<"GCTATTCGACTGGCGGACTAACCGATCAACTGGATGACCAGCTAACTGGCGGATGA\n";GCAT();
HELIX<<"TCAAGCGGGTGGGTAAATCGCCCGCCCGGTGGTTGAGAGAGAGAAGGATCTAGAGA\n";GCAT();
HELIX<<"AGGAACTGGCTATTCGACTGGCGGACTAACCGATCAACTGGATGACCAGCTAACTG\n";GCAT();
HELIX<<"GCGGATGATCAAGCGGGTGGGTAAATCGCCCGCCCGGTGGTTGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAATTAGTTGTTCGCCTGCTCGACTGACCGACTAGCGGACTAACCGATCAACTG\n";GCAT();
HELIX<<"GCGAACTAACCGATCAACTGGATGACCAGCTAACTGGTAAATCGTATATTCGCCTG\n";GCAT();
HELIX<<"CTCGGCGAACGAACGATTGAGAGAGAGAGAGAGAGAGAGAAGGAATCGATTATCTG\n";GCAT();
HELIX<<"CCTGGCGGCCAACCAAGCGGGTGGCGTAGTTAGATGAATACACGGCGGAGCGTGTG\n";GCAT();
HELIX<<"CGTGAATAAGTAAGCGCGTGAGCAAACGGCGGAGTAAGCGGATAAGCAGATGAGTG\n";GCAT();
HELIX<<"TACGCGTGAGCGCGTGAGCAAATAGATAGCGGAGTGGATACGTGAGTGCACGGCGG\n";GCAT();
HELIX<<"ATAGTGCAATAGGCGGGATAAATATATGCTAAGCGGGCGGGTGGTTGAGAGAAGGA\n";GCAT();
HELIX<<"ATTGACTGCCTGGCTAACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGACCG\n";GCAT();
HELIX<<"TCTGCCTGATTAACTAACCGCCTGACCAATCGACGATTGAGAGAGAGAAGGAACCA\n";GCAT();
HELIX<<"GTTGGCGGGCGAACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGTCAA\n";GCAT();
HELIX<<"TCAAGCGGGTGGTGCAGTGGGCGGCCTACCTAGCGGACCGTCTGCCTGATTAACTA\n";GCAT();
HELIX<<"ACCGCCTGACCAATCGGCGGTCAATCAAGCGGGTGGTCCAGTGGACGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGTCAAGCGGGTGG\n";GCAT();
HELIX<<"ATAAATAAGCGGGTGGTTGAGAGAAGGAACTGGCTATTCGACTGGAGAAGGAAGGA\n";GCAT();
HELIX<<"ACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGTCAAGCGGGTGGGTGG\n";GCAT();
HELIX<<"TTGAGAGAGAGAGAGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGCGTAGTTAAGTGGATACGTGAGTGCACGGCGGGATATGTGAGTAGACGAGTG\n";GCAT();
HELIX<<"CACGGCGGAATAGATGGCGGAGTGAGTAGACGCACGTGCAAATATACGCTAAGCGG\n";GCAT();
HELIX<<"GCGGGTGGTTGAGAGAAGGAATCGACCAGTTAGCGGCTAACTAAGCGGGTTATCTG\n";GCAT();
HELIX<<"ACTAAGTGACTAGTCGCTCGTCCAATTATTCGTTGAGAGAAGGAATCGACCAGTTA\n";GCAT();
HELIX<<"GTAAACCAATTGGTTAATTACTCGACTGGCGAACGATTGAGAGAGAGAAGGATTCG\n";GCAT();
HELIX<<"CCTGCTCGACCAGTTAATTGGCGGACTAACCGGTTAACCAGTTGACTGTTCGCCTG\n";GCAT();
HELIX<<"ACCGCCTGACCAATTAGTTATACAGTTATCTGACTAAGTGACTAGTCGCTCGTCCA\n";GCAT();
HELIX<<"ATTATTCGTGTATTGAGAGAGAGAGAGAGAGAAGGAGTCGATTAATTACCTGTTCG\n";GCAT();
HELIX<<"CCTGCTCGACCGCCCGTATACCGGTCGGGCGAACTAACCGATCAACTGGCAAGCGG\n";GCAT();
HELIX<<"ACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGACGATTGAGAGAAGGAGTCG\n";GCAT();
HELIX<<"ATTAATTACCTGTTCGCCTGCTCGACCGCCCGTATACCGGCTGGGCGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCAAGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCG\n";GCAT();
HELIX<<"ACGATTGAGAGAAGGAGAGAGAGAGAGAGAGAAGGAGTTGATTACTCGGCGGGCGA\n";GCAT();
HELIX<<"ACCAGTTAGCTGACTGCCCAGCGGTCAAGCGGCCGGTTGAGCGGACCAGTTAGCTG\n";GCAT();
HELIX<<"ACTGCCCAGCGGCCAAGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTA\n";GCAT();
HELIX<<"TTCGTTGAGCGGACCAGTTAGCTGACTGCCCAATGAATGAACGAGAGAAGGATTCA\n";GCAT();
HELIX<<"GAGAAGGAAGGATTCGCCTGCTCGACCAGTTAATTGGCGGACCAGCTGGCAAGCGG\n";GCAT();
HELIX<<"GCCAACTGGCTAACCACCCATTGAGAGAAGGAAGGAACCAGTTGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACTGACCGACTAGCGGCCTGACTGTTCGCCTGGATGACCAGCTAACTGTTGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAAGGAAGGACCTGACTGTTCGCCTGGATGACCAGCTAACTGGTAAATTA\n";GCAT();
HELIX<<"CCCGACTGGTTAGCGAGTGGGTGGACGATTGAGAGAGAGAGAGAAGGAAGGAATCG\n";GCAT();
HELIX<<"ATTATCTGCCTGGCGGCCAACCAAGCGGGTGGCGTAGTTAAGTGGATACGTGAGTG\n";GCAT();
HELIX<<"CACGGCGGAGTGAGTAGACGCACGTGCAAATAGCGGGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"TTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTG\n";GCAT();
HELIX<<"GTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCA\n";GCAT();
HELIX<<"GTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGGGTGGGCGG\n";GCAT();
HELIX<<"AGCAGGTGCTAAGCGGGCGGGTGGTTGAGAGAAGGAAGGAATTGACTGCCTGGCTA\n";GCAT();
HELIX<<"ACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGACCAGCTGACGATTGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAAGGAAGGAGCTGATTAGAGAAGGAAGGATTCAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"CCTGACTGTTCGCCTGGATGACCAGCTAACTGGTAAATCGGCTAATTATTCGACTG\n";GCAT();
HELIX<<"GCGAACGATTGAGAGAAGGAAGGAAGGACCTGACTGTTCGCCTGGATGACCAGCTA\n";GCAT();
HELIX<<"ACTGGTAAATCGGCTAACTGACCGCTCGGCGAACGATTGAGAGAGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGGTGGAGTGGATACGTGAGTG\n";GCAT();
HELIX<<"CACGGCGGAGTGAGTAGACGCACGTGCAAATAGCGGGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"TTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTG\n";GCAT();
HELIX<<"GTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCA\n";GCAT();
HELIX<<"GTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGGGTGGGCGG\n";GCAT();
HELIX<<"GATGAGCAGGTAAGTGGCGGGATAAGCGAGTAAGTGCTAAGCGGGCGGGTGGTTGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGAATTGACTGCCTGGCTAACCAGTTAACTGGCGAATCGACCA\n";GCAT();
HELIX<<"GTTAGCAAGCGGACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCA\n";GCAT();
HELIX<<"ATTAGTTATACAACCAGTTAGCTGACTGCCCATGTAACGATTGAGAGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGACCTGACTGTTCGCCTGGATGACCAGCTAACTGGTAAATTACCCGACTG\n";GCAT();
HELIX<<"GTTAGCGAACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTA\n";GCAT();
HELIX<<"GTTATACAACCAGTTAGCTGACTGCCCATGTAGTAAATCGTATATTCGCCTGCTCG\n";GCAT();
HELIX<<"GCGAACGAACGATTGAGAGAGAGAAGGAAGGATCTAGCGGTTTGGCCAACCAGCTA\n";GCAT();
HELIX<<"ACTGGCGGGCGAACGGCCTGACTGTTCGCCTGGATGACCAGCTAACTGGTAAATTG\n";GCAT();
HELIX<<"ATTAATTAGCTGGCGAACGAACGATTGAGAGAGAGAGAGAAGGAAGGACCTGACTG\n";GCAT();
HELIX<<"TTCGCCTGGATGACCAGCTAACTGGTAAATCGGCTAATTATTCGACTGGCGAACGA\n";GCAT();
HELIX<<"TTGAGAGAGAGAGAGAAGGAAGGAGCCAACTGGCTAACCACCCAGCGGTCAAGCGG\n";GCAT();
HELIX<<"ACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTATACA\n";GCAT();
HELIX<<"ACCAGTTAGCTGACTGCCCATGTAGCGGATGAGCGGGTGGGTAAAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATAGTGGTTGAGAGAGAGAGAGAAGGAAGGAACTAACCGATCAACTG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTGGGATATGTGCACGTACGAGTGCACGTGCAGCGGAGTG\n";GCAT();
HELIX<<"AGTAGACGCACGTGCAAATATATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTG\n";GCAT();
HELIX<<"TTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTA\n";GCAT();
HELIX<<"GCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTG\n";GCAT();
HELIX<<"CCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGGGTGGGCGGTCAAGCGGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGAGGACGTAGTGGGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACCAGCTGGCGGCCAACCAAGCGGGTGGCGTAGTGGGCAAGCGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGACGTAGTGGGTGGGCGGCCAACCAAGCGGGCCAACTGGCTAACCACCCAGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGCGTAGTGGGCAAGCGGGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGAGGACGTAGTGG\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCG\n";GCAT();
HELIX<<"CCTGACCAATTAGTTATACAACCAGTTAGCTGACTGCCCATGTAGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGCGTAGTGGGCAAGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGTCTATTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAAGGATCTA\n";GCAT();
HELIX<<"GAGAGAGAAGGAGAGAAGGAGAGAAGGAACTAACCGATCAACTGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGCTTGATTAACCAGCTGGCGGAATGAACGAGCGCGTGGCGAACGATTGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGCTTGATTAACCAGCTGGCGGGGCAAGCGCACGCATGAGTGTACGCGTG\n";GCAT();
HELIX<<"TATAAGTGAGTAGACGCACGTGCAAATAGCGAGATATGTGCACGTACGAGTGCACG\n";GCAT();
HELIX<<"TGCAGCGGAGTGAGTAGACGCACGTGCAAATAACGATTGAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTGACTGCCCAGCGGTCAAGCGG\n";GCAT();
HELIX<<"CCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGGCCAAGCGGGTTATCTGACTA\n";GCAT();
HELIX<<"AGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGGACCAGTTAGCTGACTGCCCA\n";GCAT();
HELIX<<"ATGAATGAACGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCGATCAACTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGCTTGATTAACCAGCTGGCGGAGTAAGCGGATAAGCAGATG\n";GCAT();
HELIX<<"AGTGTACGCGTGTATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGA\n";GCAT();
HELIX<<"CTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGA\n";GCAT();
HELIX<<"ATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGG\n";GCAT();
HELIX<<"ATGAGCGGTCGGGCGGGAGAAGGAAGGAAGGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"GCGAACGATTCAGGCAAGCGCACGCATGAGTGTACGCGTGTATAAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATAGCGAAGTGAGTAGACGCACGTGCAAATATATAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCG\n";GCAT();
HELIX<<"ACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGACGATTGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCAACCAAGCGGGTGGCTTGATTAACCAGCTGGCGGAGCAAGTA\n";GCAT();
HELIX<<"CGCGGGTAAGCGGATACGTGTATAGGCAAGTGGGTAAGCACGCATATAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"TTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCAACCAAGCGGGTGGGCGAGATATGTGCACGTACGAGTGCACG\n";GCAT();
HELIX<<"TGCAGCGGAGTGAGTAGACGCACGTGCAAATATCAAAGTGAGTAGACGCACGTGCA\n";GCAT();
HELIX<<"AATATATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGA\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGG\n";GCAT();
HELIX<<"ATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGG\n";GCAT();
HELIX<<"TCGGGCGGCCAACCAAGCGGGTGGACGATTGAGTGGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"CGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAAGGATCTAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGGTCGATTAATTAGCTA\n";GCAT();
HELIX<<"GCGGAGCAAGTACGCGGGTAAGCGGATACGTGTATAGGCAAGTGGGTAAGCACGCA\n";GCAT();
HELIX<<"GCGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAGAGAAGGAAGGACCAACCAAGCGGGTGGGCGGAGGAATTAGTTGTTCGCCTG\n";GCAT();
HELIX<<"CTCGACTGACCGACTAGCGGCCCGCTCGATTAGTCGACTGTTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"CCCGCTCGATTAGTCGACTGGTAAATTACCCGACTGGTTAGCGAAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATATATACCGGTCGGGTAAAGTAAGCGGATAAGCAGATGAGTGTACG\n";GCAT();
HELIX<<"CGTGAGCGCGTGAGCAAATAGATAGTAAATCGTATATTCGCCTGCTCGGCGAACGA\n";GCAT();
HELIX<<"ACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAACCAGTTGGCGGGCGACCCGCTCGATTAGTCGACTGGTAAGTTGACCGACCA\n";GCAT();
HELIX<<"GCTAGCGAACGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGAGGATTCAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGACCCGCTCG\n";GCAT();
HELIX<<"ATTAGTCGACTGGTAAATCGGCTAATTATTCGACTGGCGAACGATTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAAGGACTCGACTGCCTGTCTGCTCGGTTAGCGGACAATCGGTTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGACCCGCTCGATTAGTCGACTGGTAAATCGGCTAATTATTCGACTGGCGAACGA\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTAGTGGTTGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAAGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTGACTGCCCAGCGG\n";GCAT();
HELIX<<"TCAAGCGGCCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGGCCAAGCGGGTTA\n";GCAT();
HELIX<<"TCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGGACCAGTTAGCTG\n";GCAT();
HELIX<<"ACTGCCCAATGAATGAACGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCGATCA\n";GCAT();
HELIX<<"ACTGGCGGCCAACCAAGCGGGTGGAGGAAGCAAGTACGCGGGTAAGCGGATACGTG\n";GCAT();
HELIX<<"TATAGGCAAGTGGGTAAGCACGCATATAGTGGGCGGCCAACCAAGCGGTTCGACTG\n";GCAT();
HELIX<<"CCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCA\n";GCAT();
HELIX<<"GCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTG\n";GCAT();
HELIX<<"ACTGCCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGGGTGGGCGAACGATTGA\n";GCAT();
HELIX<<"GCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGAGAGAAGGATCTA\n";GCAT();
HELIX<<"GAGAGAGAGAGAAGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGACTCGACTGCCTGTCTG\n";GCAT();
HELIX<<"CTCGGTTAGCGGCCTGCTCGTCTGACTGTTGAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"GAGAAGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGCTTGATTAACCA\n";GCAT();
HELIX<<"GCTGGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGGCGAACGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"TTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTGACTGCCCAGCGGTCAAGCGG\n";GCAT();
HELIX<<"CCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGGCCAAGCGGGTTATCTGACTA\n";GCAT();
HELIX<<"AGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGGACCAGTTAGCTGACTGCCCA\n";GCAT();
HELIX<<"ATGAATGAACGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCGATCAACTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGAAGTAAGCGGATAAGCAGATGAGTGTACGCGTGTATA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGA\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTATTGAGAGAAGGATCTAGAGAGAGAGAGAAGGAACTAACCGATCAACTG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTGGCGTAGTTATCTAGTGGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"CGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAAGGAGAGAAGGAGAGAAGGA\n";GCAT();
HELIX<<"ACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGCTTGATTAACCAGCTGGCGG\n";GCAT();
HELIX<<"CATGAGCAAGTGTATGTATAGATATGTGCACGTACGAGTGCACGTGCAGCGAACGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGAGGAATCGATTATCTGCCTGGCGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGCGTAGTTACGTAGTTAGTGGTTGAGAGAAGGAAGGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTGACTGCCCAGCGG\n";GCAT();
HELIX<<"TCAAGCGGCCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGGCCAAGCGGGTTA\n";GCAT();
HELIX<<"TCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGGACCAGTTAGCTG\n";GCAT();
HELIX<<"ACTGCCCAATGAATGAACGAAGGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCGGCCAACCAAGCGGGTGGGCGGAGGAAGGACCAACCAAGCGGCGTA\n";GCAT();
HELIX<<"GTGGGCGGGCGGGCGGCCAAAGTGAGTAGACGCACGTGCAAATATATAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"TTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGACCAACCAAGCGGGTGGGTAAAGCAGGTGTCAACTAAGCGG\n";GCAT();
HELIX<<"GCGGGCGGCGTAGTGGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTACGTAGTGG\n";GCAT();
HELIX<<"CGTAGTGGGCGGCCAACCAAGCGGAGTGAGTAGACGCACGTGCAAATATATAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGGTAAAGCAGGTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTA\n";GCAT();
HELIX<<"CGTAGTGGCGTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGCGGGAGAAGGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGGCGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGCCAA\n";GCAT();
HELIX<<"AGTAAGCGGATAAGCAGATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATATCAA\n";GCAT();
HELIX<<"CTAAGCGGGCGGCGTAGTGGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTACGTA\n";GCAT();
HELIX<<"GTGGCGTAGTGGGCGGCCAACCAAGCGGAGTGAGTAGACGCACGTGCAAATATATA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGA\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGG\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGAAGGAAGGACCAACCAAGCGGGTGGGTAAAGTAAGCGGATA\n";GCAT();
HELIX<<"AGCAGATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATAGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"CGTAGTGGCGTACGTACGTAGTGGCGTAGTGGGCGGCCAACCAAGCGGCGTAGTGG\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTACGTAGTGGGTGGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"CGTAGTTACGTAGTTAGTGGTTGAGAGAAGGATCTAGAGAGAGAAGGAGAGAAGGA\n";GCAT();
HELIX<<"ACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"CGTAGTGGCGTACGTAGTTACGTAGTGGTTGAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTACGTAGTTACGTA\n";GCAT();
HELIX<<"GTTACGTAGTTACGTAGTTACGTAGTTACGTAGTTACGTAGTTACGTAGTTAGTGG\n";GCAT();
HELIX<<"TTGAGAGAGAGAGAGAGAGAGAGAAGGAACTAACCGATCAACTGGAGAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGACCAGTTACCTGGCGGACTAACCGACCAGTTAGCGA\n";GCAT();
HELIX<<"ACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGAGGAATCGATTATCTGCCTGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGCGTAGTGGCGTACGTAGTTACGTACGTAGTTACGTACGTAGTTACGTAGTGG\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGAATAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAAATACGTACGTAGTTACGTAGTGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGCCTAGCGGTACGTGTGAGTAGATAAGTGCACGAGCGCGTGAATA\n";GCAT();
HELIX<<"CACGGCGGCACGAGTGCATGCCGGTCGAGCGGGATATGTGCACGTACGAGTGCACG\n";GCAT();
HELIX<<"TGCAGCGGCCTACGTACGTAGTTACGTAGTGGGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AATAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAAATA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTACGTACGTAGTTACGTAGTGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGATTAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAATTACGTACGTAGTTACGTAGTGG\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGCCTAGCGGCGTGGGCAAGCATACGGCGGGATATGTGCACGTACGAGTGCACG\n";GCAT();
HELIX<<"TGCAGCGGTATGAGCAGGTAGGTAGCGGAGTAAGCGGATAAGCAGATGAGTGTACG\n";GCAT();
HELIX<<"CGTGGCGGCGTGGGCAAGTGGCGGGATGAATAGGTAGGTAAATATATGAGCAGATA\n";GCAT();
HELIX<<"AATGGCGGTACGAATATGTGCACGAACGAGTGGCGGAACGAATAGGTGAGTGGCGG\n";GCAT();
HELIX<<"AGTGAGTAGACGCACGTGCAAATAGCGATACGACGACTGAGCGGCCTACGTACGTA\n";GCAT();
HELIX<<"GTTACGTAGTGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGATTAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAATTACGTACGTAGTTACGTACGTAGTTACGTAGTGGTTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGACATGAGCAAGTGTATG\n";GCAT();
HELIX<<"TATAGATATGTGCACGTACGAGTGCACGTGCAGCGAACGATTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAATCGATTATCTGCCTG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGTACACGCGCACGAGTGTACGTACGGCGGAGTGGATACGTG\n";GCAT();
HELIX<<"AGTGCACGGCGGCGTGAATAGCGGAACGAATAGATACGTGAGCAGATATGTGAGTG\n";GCAT();
HELIX<<"TGTAGCGGCGTAGTGGTTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCA\n";GCAT();
HELIX<<"ATCGGCGGCCAACCAAGCGGGTGGAGGAATCGACCAGTTAGTAAATTGACTGCCTG\n";GCAT();
HELIX<<"GCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTACGTACGTAGTTA\n";GCAT();
HELIX<<"CGTACGTAGTTAGCGGGCGGGCGGGCGGGCGGGGTGAATAGCGGTGCAAATATGTG\n";GCAT();
HELIX<<"GCGGTATGAGCGGATACGTGGCGGCGTGAATAGCGGAGTAAGCGGATAAGCAGATG\n";GCAT();
HELIX<<"AGTGTACGCGTGGCGGCGTGGGCAAGTGGCGGAACGAATAGGTGAGTGGCGGAGTG\n";GCAT();
HELIX<<"AGTAGACGCACGTGCAAATAGCGATACGACGAGCGGAGCAGATACGTGAATAGCGG\n";GCAT();
HELIX<<"CGTGGGCAAGTGGCGGAGCGAACGCGTGAGCACATGAGTGGCGGGGTGAGCACACG\n";GCAT();
HELIX<<"AGTGAACGCGTGAATACACGTGCATTAACGTACGTAGTTACGTAGTGGGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGTACAAGTGGATACGTGAGTGCACGGCGG\n";GCAT();
HELIX<<"CGTACGTAATAGTGCACGTACGTAATAGGCGGAATACACGGCGGCGTACGTAATAG\n";GCAT();
HELIX<<"GATACGTACGTAATAGGCGGGATAAATATATGTGTAGCGGGCGGCGTAGTGGTTGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGGAAGGATTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAATCGGCCAACCGCTCGGCGGTCTG\n";GCAT();
HELIX<<"TTCGACTGCTCGTATGACCGGTTACCTGTTCGAGTAACCGGTTAACCAGTTGACTG\n";GCAT();
HELIX<<"TTCGCCTGACCGCCTGACCAATTAGTTATTGAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTA\n";GCAT();
HELIX<<"ACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAGCTGATTA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGGAAGGAAGGATTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCA\n";GCAT();
HELIX<<"ATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGAATCGACCAGTTAGCGG\n";GCAT();
HELIX<<"CTAACTAAGCGGTCTGTTCGACTGCTCGTATGACCGGTTACCTGTTCGAGTAACCG\n";GCAT();
HELIX<<"GTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTATTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCG\n";GCAT();
HELIX<<"TCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAACCAGTTGGCGGGCGAGCGATCTGTTCGACTGCTCGTATGACCG\n";GCAT();
HELIX<<"GTTACCTGTTCGAGTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCA\n";GCAT();
HELIX<<"ATTAGTTAGCGGTCAATCAAGCGGATAGGATAATAGACGAGCGGCCTACCTAGCGG\n";GCAT();
HELIX<<"GCGATCTGTTCGACTGCTCGTATGACCGGTTACCTGTTCGAGTAACCGGTTAACCA\n";GCAT();
HELIX<<"GTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTAGCGGTCAATCAAGCGGATAG\n";GCAT();
HELIX<<"GTTAATAGACGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGATTCAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTG\n";GCAT();
HELIX<<"ATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTA\n";GCAT();
HELIX<<"GTTACGTACGTAGTTACGTACGTAGTTAGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGCGCGGGTAAGTGAGCGTACGAGTGGCGGCACGTGTGGATAGCGGCGTG\n";GCAT();
HELIX<<"GGCAAGCATACGGCGGGATATGTGCACGTACGAGTGCACGTGCAGCGGAGCGAATG\n";GCAT();
HELIX<<"AGCGAGCAGATAGCGGCGTGAATAGCGGAGTAAGCGGATAAGCAGATGAGTGTACG\n";GCAT();
HELIX<<"CGTGGCGGCGTGGGCAAGTGGCGGAACGAATAGGTGAGTGGCGGAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATAGCGATACGACGAGTAACGTACGTAGTTACGTACGTAGTTACGTA\n";GCAT();
HELIX<<"CGTAGTTACGTAGTGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"CGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGTACACGCGCACGAGTGTACGTACGGCGGAGTGGATACGTGAGTGCACGGCGG\n";GCAT();
HELIX<<"CGTGAATAGCGGAGTGCGCAAGCACGTGTGTAGCGGCGTAGTGGTTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCG\n";GCAT();
HELIX<<"TCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAATCGACCAGTTAGTAAACCAATTGGTTAATTACTCGACTG\n";GCAT();
HELIX<<"GCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGAAGGAAGGAAGGAAGGAATCGACCAGTTAGTAAATTG\n";GCAT();
HELIX<<"ACTGCCTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCA\n";GCAT();
HELIX<<"ATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGAAGGACTCGACTGCCTG\n";GCAT();
HELIX<<"TCTGCTCGGTTAGCGGACAATCGGTTGAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCG\n";GCAT();
HELIX<<"CCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGATCTAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"ACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAAGGAAGGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTGGAGGAAGGAAGGATTTGGCCAACCAGCTAACTGGCGG\n";GCAT();
HELIX<<"GCGAGCGATCTGTTCGACTGCTCGTATGACCGGTTACCTGTTCGAGTAACCGGTTA\n";GCAT();
HELIX<<"ACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTAGCGGACGGTCAAGCGG\n";GCAT();
HELIX<<"ATAGTGCAATAGACGAGCGGGTAGGTAGGCGGGCGATCTGTTCGACTGCTCGTATG\n";GCAT();
HELIX<<"ACCGGTTACCTGTTCGAGTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTG\n";GCAT();
HELIX<<"ACCAATTAGTTAGCGGACGGTCAAGCGGATAGTCCAATAGACGAACGATTGAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"ACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAAGGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTACGTACGTAGTTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTAGTGGTTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAACCAGTTGGCGGGCGAACGG\n";GCAT();
HELIX<<"AGCAAGTACGCGGGTAAGCGGATACGTGTATAGGCAAGTGGGTAAGCACGCAGCGA\n";GCAT();
HELIX<<"ACGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGATTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGAATCGATTATCTGCCTG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTACGTACGTAGTTACGTACGTA\n";GCAT();
HELIX<<"GTTAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGTATGAGCGCACGGATAAGCAGATAAATGACGGACGGACGGGCGG\n";GCAT();
HELIX<<"AACGAGCGGATAGATAAATACGTGGCGGAGCAAGTACGCGGGTAAGCGGATACGTG\n";GCAT();
HELIX<<"GCGGGGCAAGTGGGTAAGCACGCAGCGGAGCAGATACGTGAATAGCGGAGTGAGTA\n";GCAT();
HELIX<<"GACGCACGTGCAAATAGCGATACGACGAACGGCGTACGTAGTTACGTAGTGGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGGAAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGCGCGGGTAAGTGAGCGTACG\n";GCAT();
HELIX<<"AGTGGCGGAGTGGATAAGCGGACGGGTAAGTGGCGGTATGCACGAGCACGTGAGTG\n";GCAT();
HELIX<<"GCGGAGCGAACGAACGAGTGTACGTACGGCGGCGTGAATAGCGGCGTGGGCAAGTG\n";GCAT();
HELIX<<"GCGGAGCGAACGCGTGAGCACATGAGTGGCGGGGTGAGCACACGAGTGAACGCGTG\n";GCAT();
HELIX<<"AATACACGTGCACGTACGTAGTTACGTAGTGGGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AGCGGATAGGTGGCGGCACGTGTGGATAGCGGCGTGGGCAAGCATACGGCGGGATA\n";GCAT();
HELIX<<"TGTGCACGTACGAGTGCACGTGCAGCGGAGCGAATGAGCGAGCAGATAGCGGCGTG\n";GCAT();
HELIX<<"AATAGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGGCGGCGTGGGCAAGTG\n";GCAT();
HELIX<<"GCGGAACGAATAGGTGAGTGGCGGAGTGAGTAGACGCACGTGCAAATAGCGATACG\n";GCAT();
HELIX<<"ACGAGTAACGTACGTAGTTACGTACGTAGTTACGTAGTGGGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGTACACGCGCACGAGTGTACGTACGGCGGAGTGGATA\n";GCAT();
HELIX<<"CGTGAGTGCACGGCGGCGTGAATAGCGGAGTGCGCAAGCACGTGTGTAGCGGGCGG\n";GCAT();
HELIX<<"CGTAGTGGTTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGAGGAAGGAATCGACCAGTTAGTAAACCAATTGGTTA\n";GCAT();
HELIX<<"ATTACTCGACTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGAATCGACCAGTTAGTAA\n";GCAT();
HELIX<<"ATTGACTGCCTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGACTCGACTGCCTGTCTG\n";GCAT();
HELIX<<"CTCGGTTAGCGGACAATCGGTCGGTTGAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGATCTAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"CGTAGTGGCGTACGTAGTTACGTACGTAGTTACGTACGTAGTTAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGTACGTGTGAACGAACGAGTG\n";GCAT();
HELIX<<"TACGTACGGATGTGTGGGTAGGTATGCAGCGGAGCAAGTACGCGGGTAAGCGGATA\n";GCAT();
HELIX<<"CGTGAGTGGGTGGCGGGGCAAGTGGGTAAGCACGCAGCGGAGCAGATACGTGAATA\n";GCAT();
HELIX<<"GCGGTACGAATATGTGCACGAACGAGTGGCGGAACGAATAGGTGAGTGGCGGAGTG\n";GCAT();
HELIX<<"AGTAGACGCACGTGCAAATAGCGATACGACGACGTACGTAGTTACGTAGTGGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"TACACGCGCACGAGTGTACGTACGGCGGAGTGGATACGTGAGTGCACGGCGGCGTG\n";GCAT();
HELIX<<"AATAGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGGCGGAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATAGCGATACGACGAGCGGGATAAATATATGTGTACGTACGTAGTTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTACGTAGTGGTTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTA\n";GCAT();
HELIX<<"ACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAATCGACCAGTTA\n";GCAT();
HELIX<<"GTAAACCAATTGGTTAATTACTCGACTGGCGAACGATTGAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTG\n";GCAT();
HELIX<<"ATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAATCGACCA\n";GCAT();
HELIX<<"GTTAGTAAATTGACTGCCTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGTACAGATAAATATATG\n";GCAT();
HELIX<<"GCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGAGCAGATAAATGGCGGCGTG\n";GCAT();
HELIX<<"GGCAAGTGGCGGTACGAATATGTGCACGAACGAGTGGCGGAACGAATAGGTGAGTG\n";GCAT();
HELIX<<"GCGGAGTGAGTAGACGCACGTGCAAATAGCGATACGACGAGTAAGCGGCGCGGGTA\n";GCAT();
HELIX<<"AGTGAGCGTACGAGTGGCGGTATGAGCGAGCACGTGGTAATGTACGTACGTAGTTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTACGTAGTGGTTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGTAAGCG\n";GCAT();
HELIX<<"GATAAGCAGATGAGTGTACGCGTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTACGTACGTAGTTA\n";GCAT();
HELIX<<"CGTACGTAGTTAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AGTGAGTAGACGCACGTGCAAATAGCGGAGTAAGCGGATAAGCAGATGAGTGTACG\n";GCAT();
HELIX<<"CGTGAGCGCGTGAGCAAATAGATAGCGGAACGAATAAGTACGCGGGTAAGTGCGTG\n";GCAT();
HELIX<<"AGTGGTAAGCGGCGCGGGTAAGTGAGCGTACGAGTGGCGGAACGAATAAGTACGCG\n";GCAT();
HELIX<<"AGCAGGTAAGTGGCGGAGCGGATAGGTGGCGGCACGTGTGGATAGCGGCGTGGGCA\n";GCAT();
HELIX<<"AGTGGCGGCGTACGTAGTTACGTAGTGGGCGGGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGTACG\n";GCAT();
HELIX<<"AATATGTGCACGAACGAGTGGCGGAACGAATAGGTGAGTGGCGGTATGGGCAAGCA\n";GCAT();
HELIX<<"AACGGGCAGCGGGGCAAGCGTACGGCGGAGTAAGCGGATAAGCAGATGAGTGTACG\n";GCAT();
HELIX<<"CGTGAGTGGGTGGCGGAGCAGATACGTGAATAGCGGCGTGGGCAAGTGGCGGAGCG\n";GCAT();
HELIX<<"AACGCGTGAGCACATGAGTGGCGGGGTGAGCACACGAGTGAACGCGTGAATACACG\n";GCAT();
HELIX<<"TGCAGTAACGTACGTAGTTACGTACGTAGTTACGTACGTAGTTACGTAGTGGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGTACACGCGCACGAGTGTACGTACGGCGG\n";GCAT();
HELIX<<"AGTGGATACGTGAGTGCACGGCGGCGTGAATAGCGGAGTGCGCAAGCACGTGTGTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTACGTACGTAGTTACGTAGTGGTTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCG\n";GCAT();
HELIX<<"TCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"ATCGACCAGTTAGTAAATTGACTGCCTGGCGAACGATTGAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGACTCGACTGCCTGTCTGCTCGGTTAGCGGCCAGCTGG\n";GCAT();
HELIX<<"CCGGACAACCAGCTGGCCGGTTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGCGTAGTTACGTA\n";GCAT();
HELIX<<"GTTACGTAGTTACGTAGTTAGTGGTTGAGAGAGAGAGAGAGAGAAGGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTGACTGCCCAGCGGTCAAGCGG\n";GCAT();
HELIX<<"CCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGGCCAAGCGGGTTATCTGACTA\n";GCAT();
HELIX<<"AGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGGACCAGTTAGCTGACTGCCCA\n";GCAT();
HELIX<<"ATGAATGAACGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCGATCAACTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGCGTAGTTACTTGATTAACCAGCTGGCGGAGCAAGTACGCG\n";GCAT();
HELIX<<"GGTAAGCGGATACGTGTATAGGCAAGTGGGTAAGCACGCATATAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCG\n";GCAT();
HELIX<<"ACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGGCGAGATATGTGCACGTACGAGTGCACGTGCA\n";GCAT();
HELIX<<"GCGGAGTGAGTAGACGCACGTGCAAATAACGATTCAATTAGTTGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACTGACCGACTAGCGGGGCAAGTGGGTAAGCACGCAGCGAAGTGAGTAGACGCACG\n";GCAT();
HELIX<<"TGCAAATAGTAAGGCAAGTGGGTAAGCACGCAGTAAATCGTATATTCGCCTGCTCG\n";GCAT();
HELIX<<"GCGAACGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAGAGAAGGAAGGAACTGGTTAATCGAATGAACGAGCGCGTGCCGG\n";GCAT();
HELIX<<"TTAGGCGAACTAACCGATCAACTGGCAAGCGGACCAGTTAGCTGACTGCCCAGCGG\n";GCAT();
HELIX<<"ATGAGCGGTCGGGCAAGCGGACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCG\n";GCAT();
HELIX<<"CCTGACCAATTAGTTATACAACCAGTTAGCTGACTGCCCATGTAACGATTGAGAGA\n";GCAT();
HELIX<<"AGGATCTAGAGAGAGAGAGAGAGAGAGAGAGAAGGAACTAACCGATCAACTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGCGTAGTTACTTGATTAACCAGCTGGCGGAATGAACGAGCG\n";GCAT();
HELIX<<"CGTGGCGAACGATTCAATCGATTATCTGCCTGCCAACCAAATCGGCCAACCGCTCG\n";GCAT();
HELIX<<"GCGAATAGGCGAATAGATGAATAGGTGAATAGATGAATAGGTGAATAGATGAATAG\n";GCAT();
HELIX<<"GTGAATAGACAAATAGATGAATAGACAAATAGATGAATAGATGAATAGACAAATAG\n";GCAT();
HELIX<<"ATGAATAGACAAATAGACAAATAGATAAATAGACAAATAGATAAATAGACAAATAG\n";GCAT();
HELIX<<"ACGAATAGACGATTGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAGAGACCAACCAAGCGGGTGGCTTGATTAACCAGCTGGCGGGGCAAGCGCACG\n";GCAT();
HELIX<<"CATGAGTGTACGCGTGTATAAGTGAGTAGACGCACGTGCAAATAGCGAGATATGTG\n";GCAT();
HELIX<<"CACGTACGAGTGCACGTGCAGCGGAGTGAGTAGACGCACGTGCAAATAACGATTCA\n";GCAT();
HELIX<<"ACCAGTTACCTGGCGGCTCAACCGCCCGTCAAATAGGCGAATAGATGAATAGACAA\n";GCAT();
HELIX<<"ATAGACAAATAGGTGAATAGATGAATAGACAAATAGACAAATAGATGAATAGACAA\n";GCAT();
HELIX<<"ATAGGTGAATAGACAAATAGATGAATAGATGAATAGACGAATAGTTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGACCAGTTG\n";GCAT();
HELIX<<"TTCGCCTGCTCGACTGACCGACTAGCGGTGCAAATATGTGTATAAGCGCACGAGTG\n";GCAT();
HELIX<<"TATAGATAAATACGTGTATAAGCGTGTGCGTGGGCAAATACACGAGCACACAAGTG\n";GCAT();
HELIX<<"GGTGTATACGTGAATATATACACGAGTGAGCGGGTGTATACGTGGGCAAGCATACG\n";GCAT();
HELIX<<"GCGAAGTGAGTAGACGCACGTGCAAATAGTAAGGCAAGTGGGTAAGCACGCAGTAA\n";GCAT();
HELIX<<"ATCGTATATTCGCCTGCTCGGCGAACGAACGATTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGATTAGTTGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACTGACCGACTAGCGGTGCAAATATGTGTATAAGTATGTGTACGCGTGTATAAGCA\n";GCAT();
HELIX<<"AGTAAGTAAGTGGGTGAGCAAGCGCGTGAGTGGGTATGCATATAGGTGAGTGTACG\n";GCAT();
HELIX<<"AGCATACGCGTGGCGAAGTGAGTAGACGCACGTGCAAATAGTAAAGTAAGCGGATA\n";GCAT();
HELIX<<"AGCAGATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATAGTAAATCGTATATTCG\n";GCAT();
HELIX<<"CCTGCTCGGCGAACGAACGATTGAACCAGTTACCTGGCGGGTCGACCGACTATCAA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"ATAGGCGAATAGACAAATAGATGAATAGACAAATAGATGAATAGACAAATAGATGA\n";GCAT();
HELIX<<"ATAGATGAATAGATAAATAGATGAATAGACGAATAGACAAATAGGCGAATAGATGA\n";GCAT();
HELIX<<"ATAGATGAATAGATGAATAGATGAATAGATGAATAGATGAATAGACAAATAGATAA\n";GCAT();
HELIX<<"ATAGACAAATAGACGAATAGTTGAGTCGATTAATTAGCTAGCGGGTCGACCGGTTA\n";GCAT();
HELIX<<"ATTGTCAAGTCGACCGACTATTGAGCTGATTATTCAACCAGTTACCTGGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGATCGCTCG\n";GCAT();
HELIX<<"TCTGGTTAATCGGCCATTGATTCGCCTGCTCGACCAGTTAATTGGCGGCTCAATTA\n";GCAT();
HELIX<<"TTTGACCAACTGTTGAATTGACTGCCTGGCTAACCAGTTAACTGGCGATGCAAATA\n";GCAT();
HELIX<<"TGTGTATAAGCGCACGAGTGTATAGATAAATACGTGTATAAGCGTGTGCGTGGGCA\n";GCAT();
HELIX<<"AATACACGAGCACACAAGTGGGTGTATACGTGAATATATACACGAGTGAGCGGGTG\n";GCAT();
HELIX<<"TATACGTGGGCAAGCATACGGCAACTCAATTATTTGACCAACTGACGATTGAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGACCA\n";GCAT();
HELIX<<"GTTGGCGATGCAAATATGTGTATAAGCGCACGAGTGTATAGATAAATACGTGTATA\n";GCAT();
HELIX<<"AGCGTGTGCGTGGGCAAATACACGAGCACACAAGTGGGTGTATACGTGAATATATA\n";GCAT();
HELIX<<"CACGAGTGAGCGGGTGTATACGTGGGCAAGCATACGGTAAGTTGACCGACCAGCTA\n";GCAT();
HELIX<<"GCGAACGAACGAGTCGACCGGTTAATTGTCAACTCAACCGCCCGTTGAATCGCTCG\n";GCAT();
HELIX<<"TCTGGTTAATCGGCCATCAAGTCGACCGACTATTGAACCAGTTACCTGGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGATCAGCTA\n";GCAT();
HELIX<<"ATTAGTTAATCATCAAATAGGCGAATAGACAAATAGATGAATAGATGAATAGACAA\n";GCAT();
HELIX<<"ATAGACAAATAGGTGAATAGATGAATAGACGAATAGACAAATAGGCGAATAGACAA\n";GCAT();
HELIX<<"ATAGATGAATAGATGAATAGACAAATAGACAAATAGGTGAATAGATGAATAGACGA\n";GCAT();
HELIX<<"ATAGTTGAACCAGTTACCTGGCGGTTTGGCCAACCGCCCGTCAAATCAGCTAATTA\n";GCAT();
HELIX<<"GTTAATCAATGACTCAACCGCCCGTTGAACCAGTTACCTGGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGATCAGCTATCTGGTTA\n";GCAT();
HELIX<<"ATCATCAAATAGGCGAATAGACAAATAGATGAATAGACAAATAGGTGAATAGATGA\n";GCAT();
HELIX<<"ATAGACGAATAGACAAATAGGCGAATAGACAAATAGATGAATAGATGAATAGATAA\n";GCAT();
HELIX<<"ATAGATGAATAGACGAATAGACAAATAGGCGAATAGATGAATAGATAAATAGACAA\n";GCAT();
HELIX<<"ATAGGTGAATAGATGAATAGACGAATAGTTGAACCAGTTACCTGGCGGCTCAACCG\n";GCAT();
HELIX<<"ACTATCAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGATCAGCTAATTAGTTAATCAGTGAATCAGCTAATTAGTTAATCAATGA\n";GCAT();
HELIX<<"ATCAGCTATCTGGTTAATCAGTGAATCAGCTATCTGGTTAATCAATGAATCAGCTA\n";GCAT();
HELIX<<"ATTAGTTAATCAGTGAATCAGCTATCTGGTTAATCATTGAACCAGTTACCTGGCGG\n";GCAT();
HELIX<<"CTCAACCGACTAACTATCAACTCAACCGACTAACAAATCAGCTAATTAGTTAATCA\n";GCAT();
HELIX<<"TTGAACCAGTTACCTGGCGGCTCAACCGACTAACTAACTATCAAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGATCAGCTAATTA\n";GCAT();
HELIX<<"GTTAATCAGTGAATCAGCTATCTGGTTAATCAGTGAATCAGCTAATTAGTTAATCA\n";GCAT();
HELIX<<"GTGATTTGGCCAACCGCCCGTTGATTTGGCCAACCAGCTAACTGGCGAATCGCTCG\n";GCAT();
HELIX<<"TCTGGTTAATCGGCCACCAACTCAATTATTTGACCAACTGGTAAGCTAACTGGTTA\n";GCAT();
HELIX<<"ATTGCCTGGCCAGCGAACGAACGATTCAACCAGTTACCTGGCGGATCAACTGCTCG\n";GCAT();
HELIX<<"CCCGGCTAATTACCCGTCAAGTCGACCGACTATTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGGTTGATTACTCGGCGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGTTTGGCCAACCGATCGATCATCAATTTGGCCAACCGCCCGTTGA\n";GCAT();
HELIX<<"TTTGGCCAACCGATCGATCACTAATCAAGTCGACCGACTATTGATTTGGCCAACCG\n";GCAT();
HELIX<<"ATCGATCAACAAACAAACGATTCAATCGGCCAACCGCTCGGCGGATCAACCGCCCG\n";GCAT();
HELIX<<"ATTATTTGTCAACTCAATTATTTGACCAACTGTACAATCGCTCGTCTGGTTAATCG\n";GCAT();
HELIX<<"GCCATGTATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGACCAGTTACCTGGCGGCCTGGCCATTTGACCGATCGATCATCAA\n";GCAT();
HELIX<<"ATCAGCTAATTAGTTAATCAATGATTTGGCCAACCGATCGATCAATGAATCAGCTA\n";GCAT();
HELIX<<"ATTAGTTAATCATTGAATCAACTGCTCGCCCGGCTAATTACCCGATGATCAAGCGA\n";GCAT();
HELIX<<"ATCAACCGCCCGATTATTTGTCAATCAACTCAACCGACTATTAACCCGATTATTTG\n";GCAT();
HELIX<<"GCGAATCAGCTAATTAGTTAATCAGCAAATCAGCTATCTGGTTAATCAACAATTTG\n";GCAT();
HELIX<<"GCCAACCGATCGATCAACGACTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGACCAACCAAGCGGGTGGGCGAATCAACCGCCCGATTATTTGTCAATCAA\n";GCAT();
HELIX<<"CTCAACCGACTAACTATTAACCCGATTATTTGGCGAATCAGCTAATTAGTTAATCA\n";GCAT();
HELIX<<"GCAAATCAGCTATCTGGTTAATCAACAACCTGGCCATTTGACCGATCGATCAACGA\n";GCAT();
HELIX<<"CTGAGCGAATCAACCGCCCGATTATTTGTCAATCAACTCAACCGACTAACTAACTA\n";GCAT();
HELIX<<"TTAACCCGATTATTTGGCGAATCAGCTAATTAGTTAATCAGCAAATCAGCTATCTG\n";GCAT();
HELIX<<"GTTAATCAACAACCTGGCCATTTGACCGATCGATCAACGAATGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGCCCGATTATTTG\n";GCAT();
HELIX<<"GCGAATCAGCTAATTAGTTAATCAGCAAATCAGCTATCTGGTTAATCAACAATTTG\n";GCAT();
HELIX<<"GCCAACCGATCGATCAACGACTGAGTCGACCGACTAACGAACGAACGATTGAATCG\n";GCAT();
HELIX<<"CTCGTCTGGTTAATCGGCCAATGAATGATTGAAATGAACGAGCGCGTGGCGAACGA\n";GCAT();
HELIX<<"TTGATCTATGCAAATATGTGTATAAGTATGTGTACGCGTGTATAAGCAAGTAAGTA\n";GCAT();
HELIX<<"AGTGGGTGAGCAAGCGCGTGAGTGGGTATGCATATAGGTGAGTGTACGAGCATACG\n";GCAT();
HELIX<<"CGTGCCAACCAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGATCGGCCAACCGCTCGGCGAATCAACTGCTCGCCCGGCTAATTA\n";GCAT();
HELIX<<"CCCGACGATTGATCTATCTATTTGGCCAACCAGCTAACTGGCGAACGGGTCGACCG\n";GCAT();
HELIX<<"GTTAATTGACGATTGATGCAAATATGTGTATAAGCGCACGAGTGTATAGATAAATA\n";GCAT();
HELIX<<"CGTGTATAAGCGTGTGCGTGGGCAAATACACGAGCACACAAGTGGGTGTATACGTG\n";GCAT();
HELIX<<"AATATATACACGAGTGAGCGGGTGTATACGTGGGCAAGCATACGGTAAATCGGCTA\n";GCAT();
HELIX<<"ATTATTCGACTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGACCAACCAAGCGGGTGGTGCAAATATGTGTATAAGTATGTGTACGCGTG\n";GCAT();
HELIX<<"TATAAGCAAGTAAGTAAGTGGGTGAGCAAGCGCGTGAGTGGGTATGCATATAGGTG\n";GCAT();
HELIX<<"AGTGTACGAGCATACGCGTGGTAAATCGGCTAATTATTCGACTGGCGAACGATTGA\n";GCAT();
HELIX<<"TCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAATAAGTGAGAGAGAGAGCGGAGGAAACGGGTAAGCGTACGTACGAGCA\n";GCAT();
HELIX<<"AACGGCGGGACGAGCGCGTGAGTAAGCGGATAGCGGGACGAGCGCGTGGATGAGCA\n";GCAT();
HELIX<<"AATGGGCACGTGGCGGTATGAATACACGGGTGTACGCTGAGAGAGAGAGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAGCGAGCAAGTGAGTGAGTGACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AGCGAGCAAGCAAGTGAGTGAGTGACGGGAGAGCGGGCGGGCGGGCGGAGCGCACG\n";GCAT();
HELIX<<"CACGAATGGGCAACGGGAGAGCGGGCGGGCGGGCGGAGCGTATGAACAACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGAGCGTATGAACAAACAAACAAACAAACAAACAACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGACGAGCGAGTAACGGGAGAGCGGGCGGGCGGGCGGGACG\n";GCAT();
HELIX<<"AGCGGATAAATGACGGGAGAGCGGGCGGGCGGGCGGGACGAGCGGATAAATGACAA\n";GCAT();
HELIX<<"AGTGCGTGGGCAACGGGAGAGCGGGCGGGCGGGCGGGACGAGCAGATGGATGACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGGACGGGTAAATAAATACGCGACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGACGGGTATGTGCACGCGCGACGGGAGAGCGGGCGGGCGGGCGGGACG\n";GCAT();
HELIX<<"AATAGATGGATGACGGGAGAGCGGGCGGGCGGGCGGGACGAATAGATAAACAACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGAACGGGTAAGCGGATAAACAACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGAACGGGTAAGCGGATAAACAACAAAGTGTACGCGTGACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAACGGGTAAGCGTACGGGCAACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AACGGGTATGTGGATAAACAACGGGAGAGCGGGCGGGCGGGCGGAACGGGTATGTG\n";GCAT();
HELIX<<"GATAAACAACAAAGTGCGTGGGCAACGGGAGAGCGGGCGGGCGGGCGGAACGCACG\n";GCAT();
HELIX<<"CACGAGCGAGCGAACGAACAACGGGAGAGCGGGCGGGCGGGCGGAACGCACGAGCG\n";GCAT();
HELIX<<"TACGGGCAACGGGAGAGCGGGCGGGCGGGCGGAACGCACGCACGAGCGAGCGAACG\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGAACGCACGTGTGGATAAACGGGCAACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGAACGCACGTGTGGATAAACGGGCAACAAAGTGCGTG\n";GCAT();
HELIX<<"GGCAACGGGAGAGCGGGCGGGCGGGCGGAGTGAGTGAGTGACAATGCAAATATATG\n";GCAT();
HELIX<<"ACGGGAGAGCGGGCGGGCGGGCGGGATGGGTACACGGACGGACGGACGGACGGACG\n";GCAT();
HELIX<<"ACGGGAGAGCGGGCGGGCGGGCGGAATGGGTAAGCACGCGCGCGACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAATGGGTATGTGCACGCGCGCGCGACGGGAGAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGAACAAGCGCGCGAATATATGACGGGAGAGCGGGCGGGCGGGCGGAACAAGCG\n";GCAT();
HELIX<<"TGCAAATAACGGGAGAGCGGGCGGGCGGGCGGAACAAGTGCACGACAATACGCGCG\n";GCAT();
HELIX<<"GGTAAATAAATATACGGGCAACGGGAGAGCGGGCGGGCGGGCGGAACAAGTGCACG\n";GCAT();
HELIX<<"CGCGGGTAAATACGCGACGGGAGAGCGGGCGGGCGGGCGGAACAGGTAAATAGATA\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGAACAGGTATGTGGATAAACAACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGAACACACGTGTGGATAAACGGGCAACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGAATAAATAAATAGATGGATGACGGGAGAGCGGGCGGGCGGGCGGAATA\n";GCAT();
HELIX<<"AATAAATAAATAGATGGATGACGGGAGAGCGGGCGGGCGGGCGGAATATGTGAACG\n";GCAT();
HELIX<<"GGCAACGGGAGAGCGGGCGGGCGGGCGGAATATGTGAACGGGCAACAAAGTGCGTG\n";GCAT();
HELIX<<"GGCAACGGGAGAGCGGGCGGGCGGGCGGAATATATGTATGTATGACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAATATATGACAAAGTGCGTGGGCAGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"CGCGAGCGAGTAACGGGAGAGCGGGCGGGCGGGCGGCGCGGGTAAATACGCGACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGCGCGAATATATGACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"CGCGAATATATGAGCAAGTGACGGGAGAGCGGGCGGGCGGGCGGTGCGTGTGGATA\n";GCAT();
HELIX<<"AACGAACAAACAAACAACGGGAGAGCGGGCGGGCGGGCGGCACGAGCGAACAAACA\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGCACGAGCACGCGACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGTACGGGTAAATATACGGGCAACGGGAGAGCGGGCGGGCGGGCGGTACG\n";GCAT();
HELIX<<"AATAAACGAACAACGGGAGAGCGGGCGGGCGGGCGGTACGCGCGGGTAAGCGCGTG\n";GCAT();
HELIX<<"TACGACGGGAGAGCGGGCGGGCGGGCGGTACGCGCGGGTAAGCGCGTGCGTGACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGTACGCGCGGGTAAATAAATATACGGGCAACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGTACGTATGAGCGAGCGCGCGACGGGAGAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGTACGTATGAGCATACGGGCAACGGGAGAGCGGGCGGGCGGGCGGTACGTATG\n";GCAT();
HELIX<<"AATAAATATACGGGCAACGGGAGAGCGGGCGGGCGGGCGGCGTGGGCATGTGGATA\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGCGTGGGCATATGAGCGAACGAACAACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGCGTGGGCATATGAGCGAACGAACAAGTGACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGCGTGGGCATATGAGCGCGCGAGTGACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGCGTGGGCATATGAGCGCGCGCGCGACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"TGTGAATGAATGGGCAACGGGAGAGCGGGCGGGCGGGCGGTGTGCACGAACAAACA\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGCATGCACGAATAGATAAACAACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGTATGGGCAAGCGAACGAACAACGGGAGAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGTATGGGCAAGCGAACGAACAACAAAGTGCGTGGGCAACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGTATGGGCAAGCGAGTAACAAAGTGCGTGGGCAACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGTATGGGCAAGCGAGTAAGTAACGGGAGAGCGGGCGGGCGGGCGGTATG\n";GCAT();
HELIX<<"GGCAAGCGAGTAAGTAAGTAACGGGAGAGCGGGCGGGCGGGCGGTATGGGCAAGCG\n";GCAT();
HELIX<<"CGCGACGGGAGAGCGGGCGGGCGGGCGGCACAACAACACATATGAGCGCGCGACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGCACAAGCGAGTAACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"CACAAGCGAGTAAGTAACGGGAGAGCGGGCGGGCGGGCGGCACAAGCGAGTAAGTA\n";GCAT();
HELIX<<"AGTAACGGGAGAGCGGGCGGGCGGGCGGCACAAGCGCGCGACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGCACAAGCGCGCGACAAAGTGCGTGGGCAGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"CACAAATGCACGTGTGCGCGCGCGCGCGACGGGAGAGCGGGCGGGCGGGCGGCACA\n";GCAT();
HELIX<<"GGTAAATAGATAAACAACGGGAGAGCGGGCGGGCGGGCGGCACAGGTAAATACGCG\n";GCAT();
HELIX<<"CGCGACGGGAGAGCGGGCGGGCGGGCGGCACAGGTAAATACGTGCGTGACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGCACAAATAAACAACGGGAGAGCGGGCGGGCGGGCGGCACA\n";GCAT();
HELIX<<"AATATATGAGCAAGTGACGGGAGAGCGGGCGGGCGGGCGGCACATATGAGCGCGCG\n";GCAT();
HELIX<<"CGCGACGGGAGAGCGGGCGGGCGGGCGGCACACACATATGAGCGCGCGACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGCACACACACACACACATATGAGCGCGCGACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGCACACACACACACACACACATATGAGCGCGCGACGGGAGAGAGA\n";GCAT();
HELIX<<"GCGGGTGAATAAGAGAGAGAGAGAAGGAACTAACCGATCAACTGGTAAATCGGCTA\n";GCAT();
HELIX<<"ATTATTCGACTGGCGAACGATTGAGAGAAGGAGAGAAGGAGAGAAGGACTCGACTG\n";GCAT();
HELIX<<"CCTGTCTGCTCGGTTAGCGGCCAGCTGGCCGGACAACCAGCTGGCCGGTTGAGAGA\n";GCAT();
HELIX<<"TCTAGAGAGAGAGAGAGAGAGAGAGAGACTTGATTAACCAGCTGGCGGACTGGTTA\n";GCAT();
HELIX<<"ATCGAATGAACGAGCGCGTGCCGGTTAGGCGAATTAGTTGTTCGCCTGCTCGACTG\n";GCAT();
HELIX<<"ACCGACTAGCGGGTAGACTGGTTAATCGATTAGCTGACTGGCTGGCAAGCGGACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGACTGACTAGTCGCTCGTCCAATTAGATATCTGACTAGCAAGCGG\n";GCAT();
HELIX<<"TTCGCCTGCTCGACCAGTTAATTGGCGGTTCGATTATCTGCTCGATCGACTGACGA\n";GCAT();
HELIX<<"GAGATTCAGAGAATAAATAAAGGATTCGCCTGCTCGACCAGTTAATTGGCGGTTCG\n";GCAT();
HELIX<<"ATTATCTGCTCGATCGACTGGCAAGCGGATTAGTCGGTCAACTGATCGCCTGGCGG\n";GCAT();
HELIX<<"TCAAGCGGGTGGGTGGTTGAGAGAGAGAAGGAATCGATTAGTTATTCGCCTGGCGG\n";GCAT();
HELIX<<"ACCAGTTACCTGGCGGAGTAAGCGCGCATATACGCGCACGAGCAGATACGTGAGTG\n";GCAT();
HELIX<<"GGTGGCGGTCAAGCGGTCGGCCAGTTGAGAGAGAGAAGGAACCAGTTACCTGGCGG\n";GCAT();
HELIX<<"ACCAGTTAGCTGACTGCCCAGCGGTCAAGCGGTCGGGCAAGCGGCCCGCTCGACCA\n";GCAT();
HELIX<<"GTTACCTGACTGGCTGGCGGTCAAGCGGCCGGTTGAGAGAAGGAATCGGCCAACCG\n";GCAT();
HELIX<<"CTCGGCGGGTTAATTATTTGTTGAGAGAGAGAGAGAATAAATAAAGGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGGCGGCCAACCAAGCGGGTGGAGTGGATACGTGAGTGCACGGCGGTACG\n";GCAT();
HELIX<<"AATATGTGCACGAACGAGTGGCGGAACGAATAGGTGAGTGGCGGGATGAGCAGGTA\n";GCAT();
HELIX<<"AGTGGCGGGATAAGCGAGTAAGTGGCGGGATGAATACACGGCGGAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATAGCGGGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGA\n";GCAT();
HELIX<<"CTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGA\n";GCAT();
HELIX<<"ATAGCCGGATAGACGAGCGGCCAACCAAGCGGACTGACTAGTCGCTCGTCCAATTA\n";GCAT();
HELIX<<"GATATCTGACTAGCGGCCAACCAAGCGGGTGGCTAAGCGGGCGGGTGGTTGAGAGA\n";GCAT();
HELIX<<"ATAAATAAAGGAATCGACCAGTTAGCGGCTAACTAAGCGGTTCGATTATCTGCTCG\n";GCAT();
HELIX<<"ATCGACTGTTGAGAGAAGGAACCAGTTGTTCGCCTGCTCGACTGACCGACTAGCGG\n";GCAT();
HELIX<<"GCTGTCTGACTAACTATCCAGCGATTCGATTATCTGCTCGATCGACTGGTAAATCG\n";GCAT();
HELIX<<"TATATTCGCCTGCTCGGCGAACGAACGATTGAGAGAGAGAGAGAAGGAACTGGTTA\n";GCAT();
HELIX<<"ATCGATTAGCTGACTGGCTGGCGGCCAACCAAGCGGGTGGGGCAAGTGGGTAAGCA\n";GCAT();
HELIX<<"CGCACCAACCAACGTAGTGGGTGGTTGAGAGAGAGAGAGAAGGATTTGGCCAACCA\n";GCAT();
HELIX<<"GCTAACTGGCGGGCGAGCTGTCTGACTAACTATCCAGTAAATTGACTGCCTGGCGA\n";GCAT();
HELIX<<"GTTAATTATTTGACGAACGAGAGAAGGATTCAGAGAAGGAAGGAGAGAAGGAAGGA\n";GCAT();
HELIX<<"ATCGGCCAACCGCTCGGCGGGCTAACTGCCTGCCTGACTGCTCGTTGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAAGGATTCAGAGAAGGAAGGAGAGAAGGAAGGAAGGATTCGCCTG\n";GCAT();
HELIX<<"CTCGACCAGTTAATTGGCGGGTCGACCAGTTAACCGCTCGTCCAGCGGTCAAGCGG\n";GCAT();
HELIX<<"GTCGACCACCTGTTCGACTGCCTGCCAACCGACTAAGCGGGCGAGTTAATTATTTG\n";GCAT();
HELIX<<"ACGAGTAACCTGATTATATATTCGCCTGCTCGACCAGTTAATTGGCGAACGATTGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGATAAATAAGCGGCCTGATTAGCGGGTCGACCAGTTAACCG\n";GCAT();
HELIX<<"CTCGTCCAGAGAAGGAGAGAAGGAAGGAAGGAGTTGATTACTCGGCGGGCGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGGCTAATTATTTGGCGGTCAAGCGGTTGGTTGAGCGGGCTAATTA\n";GCAT();
HELIX<<"TTTGGCGGCTAATCAAGCGGCCGGTTGAGCGGGCTAATTATTTGACAAACAAACGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGATTCAGAGAAGGAAGGAAGGAAGGAACCAGTTACCTGGCGG\n";GCAT();
HELIX<<"GCCAACCAATTGGCCAGCGGTCAAGCGGGCTAATTATTTGGCGGATGAGCGGCCAG\n";GCAT();
HELIX<<"TTGAGAGAAGGAAGGAAGGAGAGAAGGAAGGAAGGAAGGATTCGTTTGACCACCTG\n";GCAT();
HELIX<<"ATCGGCCAGCGGGCGAGTCGACCAGTTAACCGCTCGTCCATACAGCCAACCAATTG\n";GCAT();
HELIX<<"GCCATGTAACGAGAGAAGGAAGGAAGGAAGGATTCAGAGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAATCGACCGTTCGACTGGCGGATAGCCGGATAGCTGAAGGATTCGTTTGACCA\n";GCAT();
HELIX<<"CCTGATCGGCCAGCGGGCGAGTCGACCAGTTAACCGCTCGTCCATACAGCTAATTA\n";GCAT();
HELIX<<"TTTGTGTAACGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGATTCAGAGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAATCGACCGTTCGACTG\n";GCAT();
HELIX<<"GCGGATAGCCGGATAGCTGAAGGAGCTAACTGCCTGCCTGACTGCTCGGCGGTCAA\n";GCAT();
HELIX<<"GCGGATAGAATGATAGTTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAGTCGCTCGACTGACCGATCATTGAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGAAGGAATCGACCGTTCGACTGGCGGATAGTCGGATAG\n";GCAT();
HELIX<<"CTGAAGGAGCTAACTGCCTGCCTGACTGCTCGGCGGTCAAGCGGATAGAACGATAG\n";GCAT();
HELIX<<"TTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"GTCGCTCGACTGACCGATCATTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGATCTAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAGTCGCTCGACTG\n";GCAT();
HELIX<<"ACCGATCATTGAAGGAAGGAAGGAAGGAGAGAAGGAAGGAAGGAAGGAAGGAATCG\n";GCAT();
HELIX<<"ACCGTTCGACTGGCGGATAGTCGGATAGCTGAAGGATTCGTTTGACCACCTGATCG\n";GCAT();
HELIX<<"GCCAGCGGGCGAGTCGACCAGTTAACCGCTCGTCCATACAGCTAATTATTTGTGTA\n";GCAT();
HELIX<<"ACGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGATTCAGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGAAGGAAGGAATCGACCGTTCGACTGGCGGATAGCCGG\n";GCAT();
HELIX<<"ATAGCTGAAGGAGCTAACTGCCTGCCTGACTGCTCGGCGGTCAAGCGGATAGAGCG\n";GCAT();
HELIX<<"ATAGTTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAGTCGCTCGACTGACCGATCATTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAATCGACCGTTCGACTGGCGGATAGTCGGATAGCTGAAGGAGCTA\n";GCAT();
HELIX<<"ACTGCCTGCCTGACTGCTCGGCGGTCAAGCGGATAGCGTGATAGTTGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAGTCGCTCGACTG\n";GCAT();
HELIX<<"ACCGATCATTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGATCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAGTCGCTCGACTGACCGATCATTGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGAAGGATCTAGAGAAGGAAGGAAGGAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"ACTGGTTAATCGATTAGCTGACTGGCTGGCGGCCAACCAAGCGGGCTAACTGCCTG\n";GCAT();
HELIX<<"CCTGACTGCTCGTTGAAGGAGAGAAGGAAGGAAGGATCTAGAGAAGGAGAGAAGGA\n";GCAT();
HELIX<<"AGGATCTAGAGAGAGAAGGAAGGAGAGAAGGAAGGACCCGCTCGACCAGTTACCTG\n";GCAT();
HELIX<<"ACTGGCTGATGAATGATTGAGAGAGAGAAGGAAGGAACCAGTTGGCGGGCGACCCG\n";GCAT();
HELIX<<"CTCGACCAGTTACCTGACTGGCTGTCAATCAAAGTAAGCGCGCATATACGCGCACG\n";GCAT();
HELIX<<"AGCAGATACGTGAGTGGGTGACGAGAGAAGGAAGGATTCAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"ACTGGTTAATCGATTAGCTGACTGGCTGGCGGCCAACCAAGCGGGTGGCGTACGTA\n";GCAT();
HELIX<<"GTTACGTAGTGGTTGAAATGAACGAGCGCGTGGCGAACGATTGACGTAGTTAGGCA\n";GCAT();
HELIX<<"AGTGGGTAAGCACGCACCAACCAACGTAGTGGGTGGTTGAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"CCCGCTCGACCAGTTACCTGACTGGCTGGCGGTCAAGCGGCCGGTTGAGAGAAGGA\n";GCAT();
HELIX<<"AGGATCTAGAGAGAGAGAGAAGGATCTAGAGAAGGAACTGGTTAATCGATTAGCTG\n";GCAT();
HELIX<<"ACTGGCTGGCGGCCAACCAAGCGGGTGGCGTAGTGGTTGAAATGAACGAGCGCGTG\n";GCAT();
HELIX<<"GCGAACGATTGAGGCAAGTGGGTAAGCACGCAGTAAATCGGCTAATTATTCGACTG\n";GCAT();
HELIX<<"GCGAACGATTGATCTAGTGGTTGAGAGAGAGAGAGAAGGAGCTGTCTGACTAACTA\n";GCAT();
HELIX<<"TCCAGTAAATCGGCTAATTATTCGACTGGCGAACGATTGAGAGATCTAGAGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAGAGAGAGAGAGAGAGACTTGATTAACCAGCTGGCGGGTCGATTAATTA\n";GCAT();
HELIX<<"CCTGTTCGCCTGCTCGACCGCCCGTATACCGGTCGGGCGAATTAGTTGTTCGCCTG\n";GCAT();
HELIX<<"CTCGACTGACCGACTAGCGGGTAGACTAACCGATCAACTGGCAAGCGGTTCGCCTG\n";GCAT();
HELIX<<"CTCGACCAGTTAATTGGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCG\n";GCAT();
HELIX<<"ACGAGAGATTCAGAGAGAGAAGGATTCGCCTGCTCGACCAGTTAATTGGCGGCCTG\n";GCAT();
HELIX<<"ACTGATCGGCCAGTTAACCAATCGACCAACCGGTTAGCAAGCGGACCGTCTGCCTG\n";GCAT();
HELIX<<"GCCAATTACTCGACCACTCAACCGCCTGACCAATTAGTTAGCAAGCGGATTGACTG\n";GCAT();
HELIX<<"TTCGCCTGACCGCCTGACCAATTAGTTAGCAAGCGGTTCGACTGTCCGTCTGACTG\n";GCAT();
HELIX<<"GTTAATCGACTGTTGAGAGAGAGAGAGAAGGAACTAACCGATCAACTGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGCCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGAATAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAAATAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGCCTA\n";GCAT();
HELIX<<"GCGGTACGTGTGAGTAGATAAGTGCACGAGCGCGTGAATACACGGCGGCACGAGTG\n";GCAT();
HELIX<<"CATGCCGGTCGAGCGGGATATGTGCACGTACGAGTGCACGTGCAGCGGCCTAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AATAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAAATA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTATTGAGAGAGAGAGAGAAGGAACCAGTTGGCGGGCGAACCGTCTG\n";GCAT();
HELIX<<"CCTGATTAACTAACCGCCTGACCAATCGGCGGACGGTCAAGCGGGTGGGTGGACGA\n";GCAT();
HELIX<<"GAGAAGGATTCAGAGAAGGAAGGAACTAACCGATCAACTGAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGATAAATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGATAAATAAGCGGCCAAAGCGTGTGCGTGAATAAGTAAGCGCGTG\n";GCAT();
HELIX<<"AGCAAACGGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGAGCGCGTGAGCA\n";GCAT();
HELIX<<"AATAGATAGCGGAGCATACGGCGGAGTGGATAAGCGGACGGGTAAGTGGGTGCTAA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"TTGAGAGAAGGATCTAGAGAGAGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGCGTAGTTAAGTGGATACGTGAGTGCACGGCGGCGTGAGTGAACG\n";GCAT();
HELIX<<"GGCAGATAAGCAAACGAGCAAGCGGATACTAAGCGGGCGGGTGGTTGAGAGAAGGA\n";GCAT();
HELIX<<"ATTGACTGCCTGGCTAACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGCCTG\n";GCAT();
HELIX<<"ACTGATCGGCCAGTTAACCAATCGACCAACCGGTTAACGATTGAGAGAAGGAACTA\n";GCAT();
HELIX<<"ACCGATCAACTGGCGGCCAACCAAGCGGGTGGATAAATAAGCGGCCAACGTGAGTG\n";GCAT();
HELIX<<"AACGGGCAGATAAGCAAACGAGCAAGCGGATATCAACTAAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGTGGGCGGCCAACCAAGCGGCCTGACTGATCGGCCAGTTAACCAATCGACCA\n";GCAT();
HELIX<<"ACCGGTTAGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGAGAGAAGGAGAGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGGTGGAGTGGATA\n";GCAT();
HELIX<<"CGTGAGTGCACGGCGGAGCGTGTGCGTGGGCAAATACACGAGCACACAAGCGCGTG\n";GCAT();
HELIX<<"AGCAAATAGATACTAAGCGGGCGGGTGGTTGAGAGAAGGAATTGACTGCCTGGCTA\n";GCAT();
HELIX<<"ACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGACCGTCTGCCTGGCCAATTA\n";GCAT();
HELIX<<"CTCGACCACTCAACCGCCTGACCAATTAGTTAACGATTGAGAGAAGGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCGGCCAACCAAGCGGGTGGATAAATAAGCGGCCAAAGCGTGTGCGTG\n";GCAT();
HELIX<<"GGCAAATACACGAGCACACAAGCGCGTGAGCAAATAGATATCAACTAAGCGGGCGG\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACCGTCTGCCTGGCCAATTACTCGACCACTCAACCG\n";GCAT();
HELIX<<"CCTGACCAATTAGTTAGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGAGAGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGTGGATACGTGAGTGCACGGCGGAATGAGTGTACGCGTGAGCGCGTGAGCAAATA\n";GCAT();
HELIX<<"GATACTAAGCGGGCGGGTGGTTGAGAGAAGGAATTGACTGCCTGGCTAACCAGTTA\n";GCAT();
HELIX<<"ACTGGCGAATCGACCAGTTAGCAAGCGGATTGACTGTTCGCCTGACCGCCTGACCA\n";GCAT();
HELIX<<"ATTAGTTAACGATTGAGAGAAGGAACTAACCGATCAACTGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGATAAATAAGCGGCCAAAATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATA\n";GCAT();
HELIX<<"TCAACTAAGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGATTG\n";GCAT();
HELIX<<"ACTGTTCGCCTGACCGCCTGACCAATTAGTTAGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTATTGAGAGAAGGAGAGAAGGAGAGAAGGAATCGATTATCTGCCTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTATTGAGAGAAGGAGAGAAGGAGAGAAGGA\n";GCAT();
HELIX<<"GCTGATTAGAGAAGGATTCAGAGAAGGAAGGAATCGATTATCTGCCTGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGAGTGGATACGTGAGTGCACGGCGGTACGAGTGTGCGTGTGAGTG\n";GCAT();
HELIX<<"GATAAACGAGTGGCGGTACACGCGCACGAGTGTACGTACGGCGGAGTGGATACGTG\n";GCAT();
HELIX<<"AGTGCACGGCGGCGTGAATAGCGGTACGCGTGAATACGCGTGTACTAAGCGGGCGG\n";GCAT();
HELIX<<"GTGGTTGAGAGAAGGAAGGAATTGACTGCCTGGCTAACCAGTTAACTGGCGAATCG\n";GCAT();
HELIX<<"ACCAGTTAGCAAGCGGTTCGACTGTCCGTCTGACTGGTTAATCGACTGACGATTGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAGAGAAGGAAGGAACCAGTTGGCGGGCGATTCGACTGTCCGTCTG\n";GCAT();
HELIX<<"ACTGGTTAATCGACTGGCGGACGGTCAAGCGGGTGGGTGGACGAGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGATAAATAAGCGGCCAA\n";GCAT();
HELIX<<"TACGAGTGTGCGTGTGAGTGGATAAACGAGTGTCAACTAAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGTTCGACTGTCCGTCTGACTGGTTA\n";GCAT();
HELIX<<"ATCGACTGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGAAGGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAGAGAAGGATCTAGCGGTTTGGCCAACCAGCTAACTGGCGGGCGATTCGACTG\n";GCAT();
HELIX<<"TCCGTCTGACTGGTTAATCGACTGGCGGACGGTCAAGCGGGTGGGTGGACGATTGA\n";GCAT();
HELIX<<"GAGAGAGAGAGAGAGATCTAGAGAGAGAGAGAGAGAGAGAGAGAGAGACTTGATTA\n";GCAT();
HELIX<<"ACCAGCTGGCGGGTCGATTAATTACCTGTTCGCCTGCTCGACCGCCCGTATACCGG\n";GCAT();
HELIX<<"CTGGGCGAATTAGTTGTTCGCCTGCTCGACTGACCGACTAGCGGGTAGACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCAAGCGGACCAGTTACCTGGCGGGTTATCTGACTAAGTGACTAGTCG\n";GCAT();
HELIX<<"CTCGTCCAATTATTCGACGAGAGATTCAGAGAAGGAACTAACCGATCAACTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTA\n";GCAT();
HELIX<<"CGTAGTTAGTGGGAGAGAGAAGGAAGGACCAACCAAGCGGGTGGATGGACCAGTTA\n";GCAT();
HELIX<<"ATCGGCTATCTGGCTGACTGGCGGCCAAACCAATTATTCGCCTGCTCGACTGACCG\n";GCAT();
HELIX<<"ACTACTAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGATGGACCAGTTAATCGGCTATCTGGCTGACTGGCGGCCAA\n";GCAT();
HELIX<<"TTCGCCTGCTCGACCAGTTAATTGCTAAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGATGGACCAGTTAATCGGCTA\n";GCAT();
HELIX<<"TCTGGCTGACTGGCGGCCAAGTTGTTCGCCTGCTCGACTGACCGACTACTAAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGATGGACCAGTTAATCGGCTATCTGGCTGACTGGCGGCCAAATCGACTAACCG\n";GCAT();
HELIX<<"CCTGGCCACTAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGTCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTG\n";GCAT();
HELIX<<"CTGACTGAATCGACCAGTTATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTGTTCGACCAGTTAATTGGCGG\n";GCAT();
HELIX<<"TTCGCCTGGCTGCTGACTGAATCGATTATCTGCCTGTTGAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTGTTCG\n";GCAT();
HELIX<<"ACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGAACTGGTTAGCTGGCTATTGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGTCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGAACCA\n";GCAT();
HELIX<<"GTTGTTCGCCTGCTCGACTGACCGACTATTGAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTGTTCGACCAGTTA\n";GCAT();
HELIX<<"ATTGGCGGTTCGCCTGGCTGCTGACTGAATTAGTTGTTCGCCTGCTCGACTGACCG\n";GCAT();
HELIX<<"ACTATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGTCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGA\n";GCAT();
HELIX<<"CTGATTCGCCTGCTCGACCAGTTAATTGTTGAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTGTTCGACCAGTTA\n";GCAT();
HELIX<<"ATTGGCGGTTCGCCTGGCTGCTGACTGACCCGATTATTTGTTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGGAGAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGATCGATTAGTTATTCGCCTGGCGGACCAGTTACCTGGCGG\n";GCAT();
HELIX<<"AGTGAGTAGACGCACGTGCAAATATACGGCGGTCAAGCGGGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGTTGAGTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTACGTA\n";GCAT();
HELIX<<"GTTAGTGGGAGAGAGAAGGAAGGACCAACCAAGCGGGTGGTTCGCCTGCTCGTCTG\n";GCAT();
HELIX<<"ATCGCCTGGCGGGATATGTGCACGTACGAGTGCACGTGCAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTTCAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGGATTCGCCTGCTCGACCAGTTAATTGGCGGAGCAGGTGTTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGCGGGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGGATTCGCCTGCTCGACCAGTTAATTGGCGGGGCAAGTGGGTAAGCACGCA\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGAGGATTCGCCTGCTCGACCAGTTAATTGGCGGAGTAAGCGGATA\n";GCAT();
HELIX<<"AGCAGATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATATTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTA\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGG\n";GCAT();
HELIX<<"TTGAGAGATCTAGAGA";GCAT();HELIX.close();}
void GCAT(){cout<<char('('+'*'+'*'+'*'-'+'-'+'+'-'+'-'-'/'-'/'-')');}
void HARVEST_EMBRYO(NURSERY EMBRYO){int zap='('+'-'-'*'+'-'-'+'-'*'-'+'+')';
ifstream YOU_ARE_NOT_AUTHORIZED_TO_READ_THIS(EMBRYO.HELIX.c_str());
ofstream YOU_MUST_IMMEDIATELY_DESIST(EMBRYO.MANIFESTATION.c_str());int bam=
'('-'+'-'+'-'+'+'/'+')'-'('+'+'+'+'+'+'-'/'-')';bool bang=bam;do{int
crunch;string zowie;getline(YOU_ARE_NOT_AUTHORIZED_TO_READ_THIS,zowie);
if(YOU_ARE_NOT_AUTHORIZED_TO_READ_THIS.fail())bang=zap;crunch=bam;int
klonk='('-'+'+'-'-'*'+')'-'('-'+'+'-'-'*'+')';int whap=klonk+zap;int
klunk='('-'+'-'*'+')'-'('-'+'+'/'+')'-'('+'/'-'*'+')';int zam=
klonk*klonk+klunk*klunk+klonk*klunk;int zamm=zam-klonk;int zammm=
klonk*klunk*klonk*whap;while(crunch<zowie.length()){int kerplop=bam;
for(int whack=whap;whack>=bam;whack--){char kapow=zowie[crunch];
int thwack=klonk+whack+klonk;kerplop+=(kapow==zam?pow(klonk,klunk-whack):
(kapow==zamm?pow(klonk,klunk-thwack):(kapow==zammm?pow(klonk,klunk-thwack)+
pow(klonk,klunk-whack):bam)));crunch++;GCAT();}YOU_MUST_IMMEDIATELY_DESIST<<
char(kerplop);}}while(!bang);YOU_ARE_NOT_AUTHORIZED_TO_READ_THIS.close();
YOU_MUST_IMMEDIATELY_DESIST.close();}
