//                                                                  
//                 O--------------------------O                     
//                 | SUMNERATOR REV09 NURSERY |                     
//                 O--------------------------O                     
//                                                                  
//                                                                  
// <AUTOMATIC MANIFESTATION IS ENABLED>                             
//                                                                  
//                                                                  
// <TECHNICIAN=>     SUMNER, BRIAN
// <AUTHORIZATION=>  UCDENVER
// <GESTATION=>      
// <SEQUENCE=>       SUMNERATOR REV09 SUITE
// <SEQUENCE=>       https://github.com/C5T2B7U/sumnerator_suite
//                                                                  



#include <iostream>
#include <string>
#include <fstream>
#include <cmath>
using std::cin;
using std::cout;
using std::endl;
using std::ifstream;
using std::ofstream;
using std::string;
using std::pow;


const int EMBRYOS = 1;


struct NURSERY
{
	string ID;
	string HELIX;
	string MANIFESTATION;
};


NURSERY EMBRYO_01 = 
{
	"SUMNERATOR_REV09_BUILD_NURSERY.cpp", 
	"SUMNERATOR_REV09_BUILD_NURSERY.cpp.EMBRYO", 
	"SUMNERATOR_REV09_BUILD_NURSERY.cpp", 
};


void GCAT();
void HARVEST_EMBRYO(NURSERY EMBRYO);


void MANIFEST_01(){HARVEST_EMBRYO(EMBRYO_01);}
void IMPLANT_HELIX_01(NURSERY EMBRYO=EMBRYO_01);


bool IMPLANT_HELIX()
{
 	ofstream probe;
	probe.open(EMBRYO_01.MANIFESTATION.c_str());

	if (probe.fail())
	{
		probe.close();
		return false;
	}

	probe.close();

	IMPLANT_HELIX_01(); 

	return true;
}


void MANIFEST()
{
	MANIFEST_01();

}


void VIEW_NURSERY()
{
	cout 

 		<< "   <EMBRYO_01.ID=>   " << "\"" << EMBRYO_01.ID << "\"" << endl
 		<< "   <MANIFESTATION=>  " << "\"" << EMBRYO_01.MANIFESTATION << "\"" << "\n\n"

		<< "\n";
}







int main()
{
	cout << "\n\n\n"
		<< "                         O--------------------------O\n"
		<< "                         | SUMNERATOR REV09 NURSERY |\n"
		<< "                         O--------------------------O\n\n\n"
		<< "      o-----------------------------------------------------------------o\n"
		<< "      | THIS NURSERY WILL MANIFEST THE FOLLOWING SOURCE CODE EMBRYO(S): |\n" 
		<< "      o-----------------------------------------------------------------o\n\n";

	VIEW_NURSERY();

	cout << "                          [PRESS ENTER TO CONTINUE] ";
// 	cin.get();


	cout << "\n\n\n     DO YOU WANT TO MANIFEST THE CODE EMBRYO(S) INTO THE ACTIVE DIRECTORY?\n"
		<< "                            [ENTER \'Y\' OR \'N\' NOW]  ";
// 		{
// 			char userWantsManifestation;
// 			do
// 			{
// 				cin >> userWantsManifestation;
// 				if ((userWantsManifestation == 'N') || (userWantsManifestation == 'n'))
// 				{
// 					cout << "\n\n\n         PLEASE RUN THIS NURSERY AGAIN TO MANIFEST THE CODE EMBRYO(S).\n\n\n"
// 						<< "                           [PRESS ENTER TO EXIT] ";
// 					cin.ignore();
// 					cin.get();
// 					return -1;
// 				}
// 			}
// 			while ((userWantsManifestation != 'Y') && (userWantsManifestation != 'y'));
// 		}


	cout << "\n\n\n";
	if (!IMPLANT_HELIX())
	{
		cout << "\n\n\n                WARNING!!! CANNOT IMPLANT HELIX INTO EMBRYO(S)!\n"
			<< "              PLEASE ENABLE WRITE ACCESS TO THE ACTIVE DIRECTORY\n"
			<< "          AND RUN THIS NURSERY AGAIN TO MANIFEST THE CODE EMBRYO(S).\n\n"
			<< "                           [PRESS ENTER TO EXIT]  ";
		cin.ignore();
		cin.get();
		return -11;
	}


	cout << "\n\n\n            SUCCESSFULLY IMPLANTED HELIX INTO SOURCE CODE EMBRYO(S)\n"
		<< "                    [PRESS ENTER TO MANIFEST EMBRYO(S) NOW]\n\n\n";
// 	cin.ignore();
// 	cin.get();


	cout << "           [NOW MANIFESTING THE SOURCE CODE EMBRYO(S). PLEASE WAIT.]\n\n\n";
	MANIFEST();
	cout << "\n\n\n           EMBRYO MANIFESTATION COMPLETE. PLEASE COMPILE AND RUN THE \n" 
		<< "          SOURCE CODE WHICH HAS MANIFESTED INTO THE ACTIVE DIRECTORY.\n\n\n"
		<< "                           [PRESS ENTER TO EXIT]\n\n\n";
// 	cin.get();


	return 420-420;
}





void IMPLANT_HELIX_01(NURSERY EMBRYO){ofstream HELIX(EMBRYO.HELIX.c_str());
HELIX<<"ATAAATAAGAGAATAAATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGAATAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAAATAGAGAATAAATAAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGCCTAGCGGTACGTGTGAGTAGATAAGTGCACG\n";GCAT();
HELIX<<"AGCGCGTGAATACACGGCGGCACGAGTGCATGCCGGTCGAGCGGTACGTGTGAGCA\n";GCAT();
HELIX<<"CGTGAGTGGCGGCCTAGAGAATAAATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AATAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAAATAGAGAATAA\n";GCAT();
HELIX<<"ATAAGAGAATAAATAAGCGGCCAACGTGAGTGAACGGGCAGATAAGCAAACGAGCA\n";GCAT();
HELIX<<"AGCGGATATCAACTAAGCGGGCGGGCGGGCGGGCGGTACGTGTGAGTAGATAAGTG\n";GCAT();
HELIX<<"CACGGCAAGCGGGACGCACGAGCAAGCGGATAGAGAATAAATAAGCGGCCAATACG\n";GCAT();
HELIX<<"AGTGTGCGTGTGAGTGGATAAACGAGTGTCAACTAAGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCCACCTGCCTGCCCGTTCGCTGAATAAATAAATTGACCACCTGGCCA\n";GCAT();
HELIX<<"TCTGGTCGGTAAATCGATTAACTAATAAAACGTCAGCGTGCTGGGACGTTAGTGTG\n";GCAT();
HELIX<<"ATAATTCGTCTGACTAGTTAACTGCTCGACCGCCTGATTACTCGTATATTCGTCTG\n";GCAT();
HELIX<<"ACCACCTGACTGGTAAATTGACCACCTGGAGAATAAATAAGAGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"GAGAATGGACCAGTTAATCGGCTATCTGGCTGACTGGCGGCCAAACCAATTATTCG\n";GCAT();
HELIX<<"CCTGCTCGACTGACCGACTACTAAGAGAATGGACCAGTTAATCGGCTATCTGGCTG\n";GCAT();
HELIX<<"ACTGGCGGCCAAGTTGTTCGCCTGCTCGACTGACCGACTACTAAGAGAATGGACCA\n";GCAT();
HELIX<<"GTTAATCGGCTATCTGGCTGACTGGCGGCCAATTCGCCTGCTCGACCAGTTAATTG\n";GCAT();
HELIX<<"CTAAGAGAATGGACCAGTTAATCGGCTATCTGGCTGACTGGCGGCCAAACCAATTA\n";GCAT();
HELIX<<"ACTAACCGGTTAACCACCCGCTAAGAGAATGGACCAGTTAATCGGCTATCTGGCTG\n";GCAT();
HELIX<<"ACTGGCGGCCAAGTCGACCACCTGTTCGACTGCCTGCTAAGAGAATGGACCAGTTA\n";GCAT();
HELIX<<"ATCGGCTATCTGGCTGACTGGCGGCCAAATCGATCGCCTGTCCACCCGACTGCTAA\n";GCAT();
HELIX<<"GAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGTTGAGAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGA\n";GCAT();
HELIX<<"CTGAATCGACCAGTTATTGAGAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTG\n";GCAT();
HELIX<<"GCTGCTGACTGAACTGGTTAGCTGGCTATTGAGAGATCTGTTCGACCAGTTAATTG\n";GCAT();
HELIX<<"GCGGTTCGCCTGGCTGCTGACTGAACCAGTTGTTCGCCTGCTCGACTGACCGACTA\n";GCAT();
HELIX<<"TTGAGAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGAATTA\n";GCAT();
HELIX<<"GTTGTTCGCCTGCTCGACTGACCGACTATTGAGAGATCTGTTCGACCAGTTAATTG\n";GCAT();
HELIX<<"GCGGTTCGCCTGGCTGCTGACTGATTCGCCTGCTCGACCAGTTAATTGTTGAGAGA\n";GCAT();
HELIX<<"TCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGATTCGACTGCCTG\n";GCAT();
HELIX<<"TTTGTTGAGAGATCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGA\n";GCAT();
HELIX<<"TTCGACTGCCTGGTTGACCAGCTAGCTATTGAGAGATCTGTTCGACCAGTTAATTG\n";GCAT();
HELIX<<"GCGGTTCGCCTGGCTGCTGACTGAGTCGACCACCTGTTCGACTGCCTGTTGAGAGA\n";GCAT();
HELIX<<"TCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGACCTGATTATCTG\n";GCAT();
HELIX<<"CCCGCCCGACTGCTCGTTGAGAGAGAGAGAGAGAGACTTGATTAACCAGCTGGCGG\n";GCAT();
HELIX<<"ACTGGTTAATCGAATGAACGAGCGCGTGCCGGTTAGGCGAATTAGTTGTTCGCCTG\n";GCAT();
HELIX<<"CTCGACTGACCGACTAGCGGGTAGACTGGTTAATCGATTAGCTGACTGGCTGGCAA\n";GCAT();
HELIX<<"GCGGACCAGTTACCTGGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTA\n";GCAT();
HELIX<<"TTCGGCAAGCGGTTCGCCTGCTCGACCAGTTAATTGGCGGTTCGATTATCTGCTCG\n";GCAT();
HELIX<<"ATCGACTGACGATTGAGAGACTTGATTAACCAGCTGGCGGGTCGATTAATTACCTG\n";GCAT();
HELIX<<"TTCGCCTGCTCGACCGCCCGTATACCGGTCGGGCGAATTAGTTGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACTGACCGACTAGCGGGTAGACTAACCGATCAACTGGCAAGCGGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACCAGTTAATTGGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGACGA\n";GCAT();
HELIX<<"TTGAGAGACTTGATTAACCAGCTGGCGGGTCGATTAATTACCTGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACCGCCCGTATACCGGCTGGGCGAATTAGTTGTTCGCCTGCTCGACTGACCGACTA\n";GCAT();
HELIX<<"GCGGGTAGACTAACCGATCAACTGGCAAGCGGACCAGTTACCTGGCGGGTTATCTG\n";GCAT();
HELIX<<"ACTAAGTGACTAGTCGCTCGTCCAATTATTCGACGATTGAGAGAGAGAGAGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGACTAACCGACCAGTTAGCGAACGAGAGATTCAGAGAAGGAGAGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAACCAGTTACCTGGCGGGTTATCTGACTAAGTGACTAGTCGCTCG\n";GCAT();
HELIX<<"TCCAATTATTCGGCAAGCGGACCAGTTAGCTGACTGCCCATTGAGAGAAGGATTCG\n";GCAT();
HELIX<<"CCTGCTCGACCAGTTAATTGGCGGACTAACCGATCAACTGGATGACCAGCTAACTG\n";GCAT();
HELIX<<"GCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGTTGAGAGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAAGGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAACGTAGTTAGTGGGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGTACGTGTGAGTAGATAAGTGCACGAGCGCGTGAATACACG\n";GCAT();
HELIX<<"GCGGCACGAGTGCATGCCGGTCGAGCGGTACGTGTGAGCACGTGAGTGCGTAGTTA\n";GCAT();
HELIX<<"GTGGGAGAAGGAAGGACCAACCAAGCGGGTGGACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAACGTAGTTACGTAGTTAGTGGTTGAGAGAGAGAGAGAAGGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGGCGGCCAACCAAGCGGGTGGAGTGGATACGTGAGTGCACGGCGGGATG\n";GCAT();
HELIX<<"AGCAGGTAAGTGGCGGGATAAGCGAGTAAGTGGCGGCGTGAATAGCGGGACGTGTG\n";GCAT();
HELIX<<"AGCAGGTAGGTGCTAAGCGGGCGGGTGGTTGAGAGAAGGAATTGACTGCCTGGCTA\n";GCAT();
HELIX<<"ACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGACTAACCGATCAACTGGATG\n";GCAT();
HELIX<<"ACCAGCTAACTGACGATTGAGAGAGAGAGAGAAGGAACCAGTTGGCGGGCGAACTA\n";GCAT();
HELIX<<"ACCGATCAACTGGATGACCAGCTAACTGGTAAGCTAACTGGTTAATTGCCTGGCCA\n";GCAT();
HELIX<<"GCGAACGAGCGGCTAAGCGGCCAGACGAGAGAAGGATTCAGAGAAGGAAGGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGGCTAACTGGTTAATTGCCTGGCCAGCGGTCAAGCGGACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGATGACCAGCTAACTGGTAAGCTAACTGGTTAATTGCCTGGCCAGCGA\n";GCAT();
HELIX<<"ACGATTGAGAGAGAGAAGGAAGGAACCAGTTGGCGGGCGAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"ACTAACCGATCAACTGGATGACCAGCTAACTGTACAGCTAACTGGTTAATTGCCTG\n";GCAT();
HELIX<<"GCCAACAACCAGTGTAGCGGTCAATCAAGCGGATAGGTAAATAGGCGGGTAGGTAG\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGACCTGATTATCTGCCCGCCCGACTGCTCGGCGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGATGACCAGCTAACTGTACAGCTAACTGGTTAATTGCCTGGCCAACAA\n";GCAT();
HELIX<<"TTGGTGTAACGAGCGGTCAATCAAGCGGATAGAACGATAGGCGGGTAGGTAGGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCTGATTATCTGCCCGCCCGACTGCTCGGCGAACTAACCGATCA\n";GCAT();
HELIX<<"ACTGGATGACCAGCTAACTGTACAGCTAACTGGTTAATTGCCTGGCCAACAACTGG\n";GCAT();
HELIX<<"TGTAACGAGCGGTCAATCAAGCGGATAGCGCGATAGGCGGGTAGGTAGGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGACCTGATTATCTGCCCGCCCGACTGCTCGGCGAACTAACCGATCAACTG\n";GCAT();
HELIX<<"GATGACCAGCTAACTGTACAGCTAACTGGTTAATTGCCTGGCCAACAATCGGTGTA\n";GCAT();
HELIX<<"ACGAGCGGTCAATCAAGCGGATAGCGCGATAGGAGAAGGAAGGAAGGAACGAGAGA\n";GCAT();
HELIX<<"AGGAAGGATTCAGAGAAGGAAGGAAGGAATAAATAAGCGGGGTGAATAGCGGGATA\n";GCAT();
HELIX<<"AATACGTGGGCAAGCAGATAAATGGAGAAGGAAGGATCTAGAGAAGGAAGGAACTG\n";GCAT();
HELIX<<"GCTATTCGACTGGCGGACTAACCGATCAACTGGATGACCAGCTAACTGGCGGATGA\n";GCAT();
HELIX<<"TCAAGCGGGTGGGTAAATCGCCCGCCCGGTGGTTGAGAGAGAGAAGGATCTAGAGA\n";GCAT();
HELIX<<"AGGAACTGGCTATTCGACTGGCGGACTAACCGATCAACTGGATGACCAGCTAACTG\n";GCAT();
HELIX<<"GCGGATGATCAAGCGGGTGGGTAAATCGCCCGCCCGGTGGTTGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAATTAGTTGTTCGCCTGCTCGACTGACCGACTAGCGGACTAACCGATCAACTG\n";GCAT();
HELIX<<"GCGAACTAACCGATCAACTGGATGACCAGCTAACTGGTAAATCGTATATTCGCCTG\n";GCAT();
HELIX<<"CTCGGCGAACGAACGATTGAGAGAGAGAGAGAGAGAGAGAAGGAATCGATTATCTG\n";GCAT();
HELIX<<"CCTGGCGGCCAACCAAGCGGGTGGCGTAGTTAGATGAATACACGGCGGAGCGTGTG\n";GCAT();
HELIX<<"CGTGAATAAGTAAGCGCGTGAGCAAACGGCGGAGTAAGCGGATAAGCAGATGAGTG\n";GCAT();
HELIX<<"TACGCGTGAGCGCGTGAGCAAATAGATAGCGGAGTGGATACGTGAGTGCACGGCGG\n";GCAT();
HELIX<<"ATAGTGCAATAGGCGGGATAAATATATGCTAAGCGGGCGGGTGGTTGAGAGAAGGA\n";GCAT();
HELIX<<"ATTGACTGCCTGGCTAACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGACCG\n";GCAT();
HELIX<<"TCTGCCTGATTAACTAACCGCCTGACCAATCGACGATTGAGAGAGAGAAGGAACCA\n";GCAT();
HELIX<<"GTTGGCGGGCGAACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGTCAA\n";GCAT();
HELIX<<"TCAAGCGGGTGGTGCAGTGGGCGGCCTACCTAGCGGACCGTCTGCCTGATTAACTA\n";GCAT();
HELIX<<"ACCGCCTGACCAATCGGCGGTCAATCAAGCGGGTGGTCCAGTGGACGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGTCAAGCGGGTGG\n";GCAT();
HELIX<<"ATAAATAAGCGGGTGGTTGAGAGAAGGAACTGGCTATTCGACTGGAGAAGGAAGGA\n";GCAT();
HELIX<<"ACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGTCAAGCGGGTGGGTGG\n";GCAT();
HELIX<<"TTGAGAGAGAGAGAGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGCGTAGTTAAGTGGATACGTGAGTGCACGGCGGGATATGTGAGTAGACGAGTG\n";GCAT();
HELIX<<"CACGGCGGAATAGATGGCGGAGTGAGTAGACGCACGTGCAAATATACGCTAAGCGG\n";GCAT();
HELIX<<"GCGGGTGGTTGAGAGAAGGAATCGACCAGTTAGCGGCTAACTAAGCGGGTTATCTG\n";GCAT();
HELIX<<"ACTAAGTGACTAGTCGCTCGTCCAATTATTCGTTGAGAGAAGGAATCGACCAGTTA\n";GCAT();
HELIX<<"GTAAACCAATTGGTTAATTACTCGACTGGCGAACGATTGAGAGAGAGAAGGATTCG\n";GCAT();
HELIX<<"CCTGCTCGACCAGTTAATTGGCGGACTAACCGGTTAACCAGTTGACTGTTCGCCTG\n";GCAT();
HELIX<<"ACCGCCTGACCAATTAGTTATACAGTTATCTGACTAAGTGACTAGTCGCTCGTCCA\n";GCAT();
HELIX<<"ATTATTCGTGTATTGAGAGAGAGAGAGAGAGAAGGAGTCGATTAATTACCTGTTCG\n";GCAT();
HELIX<<"CCTGCTCGACCGCCCGTATACCGGTCGGGCGAACTAACCGATCAACTGGCAAGCGG\n";GCAT();
HELIX<<"ACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGACGATTGAGAGAAGGAGTCG\n";GCAT();
HELIX<<"ATTAATTACCTGTTCGCCTGCTCGACCGCCCGTATACCGGCTGGGCGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCAAGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCG\n";GCAT();
HELIX<<"ACGATTGAGAGAAGGAGAGAGAGAGAGAGAGAAGGAGTTGATTACTCGGCGGGCGA\n";GCAT();
HELIX<<"ACCAGTTAGCTGACTGCCCAGCGGTCAAGCGGCCGGTTGAGCGGACCAGTTAGCTG\n";GCAT();
HELIX<<"ACTGCCCAGCGGCCAAGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTA\n";GCAT();
HELIX<<"TTCGTTGAGCGGACCAGTTAGCTGACTGCCCAATGAATGAACGAGAGAAGGATTCA\n";GCAT();
HELIX<<"GAGAAGGAAGGATTCGCCTGCTCGACCAGTTAATTGGCGGACCAGCTGGCAAGCGG\n";GCAT();
HELIX<<"GCCAACTGGCTAACCACCCATTGAGAGAAGGAAGGAACCAGTTGTTCGCCTGCTCG\n";GCAT();
HELIX<<"ACTGACCGACTAGCGGCCTGACTGTTCGCCTGGATGACCAGCTAACTGTTGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAAGGAAGGACCTGACTGTTCGCCTGGATGACCAGCTAACTGGTAAATTA\n";GCAT();
HELIX<<"CCCGACTGGTTAGCGAGTGGGTGGACGATTGAGAGAGAGAGAGAAGGAAGGAATCG\n";GCAT();
HELIX<<"ATTATCTGCCTGGCGGCCAACCAAGCGGGTGGCGTAGTTAAGTGGATACGTGAGTG\n";GCAT();
HELIX<<"CACGGCGGAGTGAGTAGACGCACGTGCAAATAGCGGGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"TTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTG\n";GCAT();
HELIX<<"GTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCA\n";GCAT();
HELIX<<"GTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGGGTGGGCGG\n";GCAT();
HELIX<<"AGCAGGTGCTAAGCGGGCGGGTGGTTGAGAGAAGGAAGGAATTGACTGCCTGGCTA\n";GCAT();
HELIX<<"ACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGACCAGCTGACGATTGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAAGGAAGGAGCTGATTAGAGAAGGAAGGATTCAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"CCTGACTGTTCGCCTGGATGACCAGCTAACTGGTAAATCGGCTAATTATTCGACTG\n";GCAT();
HELIX<<"GCGAACGATTGAGAGAAGGAAGGAAGGACCTGACTGTTCGCCTGGATGACCAGCTA\n";GCAT();
HELIX<<"ACTGGTAAATCGGCTAACTGACCGCTCGGCGAACGATTGAGAGAGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGGTGGAGTGGATACGTGAGTG\n";GCAT();
HELIX<<"CACGGCGGAGTGAGTAGACGCACGTGCAAATAGCGGGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"TTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTG\n";GCAT();
HELIX<<"GTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCA\n";GCAT();
HELIX<<"GTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGGGTGGGCGG\n";GCAT();
HELIX<<"GATGAGCAGGTAAGTGGCGGGATAAGCGAGTAAGTGCTAAGCGGGCGGGTGGTTGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGAATTGACTGCCTGGCTAACCAGTTAACTGGCGAATCGACCA\n";GCAT();
HELIX<<"GTTAGCAAGCGGACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCA\n";GCAT();
HELIX<<"ATTAGTTATACAACCAGTTAGCTGACTGCCCATGTAACGATTGAGAGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGACCTGACTGTTCGCCTGGATGACCAGCTAACTGGTAAATTACCCGACTG\n";GCAT();
HELIX<<"GTTAGCGAACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTA\n";GCAT();
HELIX<<"GTTATACAACCAGTTAGCTGACTGCCCATGTAGTAAATCGTATATTCGCCTGCTCG\n";GCAT();
HELIX<<"GCGAACGAACGATTGAGAGAGAGAAGGAAGGATCTAGCGGTTTGGCCAACCAGCTA\n";GCAT();
HELIX<<"ACTGGCGGGCGAACGGCCTGACTGTTCGCCTGGATGACCAGCTAACTGGTAAATTG\n";GCAT();
HELIX<<"ATTAATTAGCTGGCGAACGAACGATTGAGAGAGAGAGAGAAGGAAGGACCTGACTG\n";GCAT();
HELIX<<"TTCGCCTGGATGACCAGCTAACTGGTAAATCGGCTAATTATTCGACTGGCGAACGA\n";GCAT();
HELIX<<"TTGAGAGAGAGAGAGAAGGAAGGAGCCAACTGGCTAACCACCCAGCGGTCAAGCGG\n";GCAT();
HELIX<<"ACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTATACA\n";GCAT();
HELIX<<"ACCAGTTAGCTGACTGCCCATGTAGCGGATGAGCGGGTGGGTAAAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATAGTGGTTGAGAGAGAGAGAGAAGGAAGGAACTAACCGATCAACTG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTGGGATATGTGCACGTACGAGTGCACGTGCAGCGGAGTG\n";GCAT();
HELIX<<"AGTAGACGCACGTGCAAATATATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTG\n";GCAT();
HELIX<<"TTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTA\n";GCAT();
HELIX<<"GCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTG\n";GCAT();
HELIX<<"CCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGGGTGGGCGGTCAAGCGGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGAGGACGTAGTGGGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACCAGCTGGCGGCCAACCAAGCGGGTGGCGTAGTGGGCAAGCGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGACGTAGTGGGTGGGCGGCCAACCAAGCGGGCCAACTGGCTAACCACCCAGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGCGTAGTGGGCAAGCGGGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGAGGACGTAGTGG\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTAACCGGTTAACCAGTTGACTGTTCGCCTGACCG\n";GCAT();
HELIX<<"CCTGACCAATTAGTTATACAACCAGTTAGCTGACTGCCCATGTAGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGCGTAGTGGGCAAGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGTCTATTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAAGGATCTA\n";GCAT();
HELIX<<"GAGAGAGAAGGAGAGAAGGAGAGAAGGAACTAACCGATCAACTGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGCTTGATTAACCAGCTGGCGGAATGAACGAGCGCGTGGCGAACGATTGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGCTTGATTAACCAGCTGGCGGGGCAAGCGCACGCATGAGTGTACGCGTG\n";GCAT();
HELIX<<"TATAAGTGAGTAGACGCACGTGCAAATAGCGAGATATGTGCACGTACGAGTGCACG\n";GCAT();
HELIX<<"TGCAGCGGAGTGAGTAGACGCACGTGCAAATAACGATTGAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTGACTGCCCAGCGGTCAAGCGG\n";GCAT();
HELIX<<"CCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGGCCAAGCGGGTTATCTGACTA\n";GCAT();
HELIX<<"AGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGGACCAGTTAGCTGACTGCCCA\n";GCAT();
HELIX<<"ATGAATGAACGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCGATCAACTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGCTTGATTAACCAGCTGGCGGAGTAAGCGGATAAGCAGATG\n";GCAT();
HELIX<<"AGTGTACGCGTGTATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGA\n";GCAT();
HELIX<<"CTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGA\n";GCAT();
HELIX<<"ATAGCCGGATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGG\n";GCAT();
HELIX<<"ATGAGCGGTCGGGCGGGAGAAGGAAGGAAGGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"GCGAACGATTCAGGCAAGCGCACGCATGAGTGTACGCGTGTATAAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATAGCGAAGTGAGTAGACGCACGTGCAAATATATAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCG\n";GCAT();
HELIX<<"ACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGACGATTGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCAACCAAGCGGGTGGCTTGATTAACCAGCTGGCGGAGCAAGTA\n";GCAT();
HELIX<<"CGCGGGTAAGCGGATACGTGTATAGGCAAGTGGGTAAGCACGCATATAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"TTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCAACCAAGCGGGTGGGCGAGATATGTGCACGTACGAGTGCACG\n";GCAT();
HELIX<<"TGCAGCGGAGTGAGTAGACGCACGTGCAAATATCAAAGTGAGTAGACGCACGTGCA\n";GCAT();
HELIX<<"AATATATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGA\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGG\n";GCAT();
HELIX<<"ATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGG\n";GCAT();
HELIX<<"TCGGGCGGCCAACCAAGCGGGTGGACGATTGAGTGGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"CGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAAGGATCTAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGGTCGATTAATTAGCTA\n";GCAT();
HELIX<<"GCGGAGCAAGTACGCGGGTAAGCGGATACGTGTATAGGCAAGTGGGTAAGCACGCA\n";GCAT();
HELIX<<"GCGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAGAGAAGGAAGGACCAACCAAGCGGGTGGGCGGAGGAATTAGTTGTTCGCCTG\n";GCAT();
HELIX<<"CTCGACTGACCGACTAGCGGCCCGCTCGATTAGTCGACTGTTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"CCCGCTCGATTAGTCGACTGGTAAATTACCCGACTGGTTAGCGAAGTGAGTAGACG\n";GCAT();
HELIX<<"CACGTGCAAATATATACCGGTCGGGTAAAGTAAGCGGATAAGCAGATGAGTGTACG\n";GCAT();
HELIX<<"CGTGAGCGCGTGAGCAAATAGATAGTAAATCGTATATTCGCCTGCTCGGCGAACGA\n";GCAT();
HELIX<<"ACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAACCAGTTGGCGGGCGACCCGCTCGATTAGTCGACTGGTAAGTTGACCGACCA\n";GCAT();
HELIX<<"GCTAGCGAACGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGAGGATTCAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGACCCGCTCG\n";GCAT();
HELIX<<"ATTAGTCGACTGGTAAATCGGCTAATTATTCGACTGGCGAACGATTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAAGGACTCGACTGCCTGTCTGCTCGGTTAGCGGGTTGACCGGCTATTCGACTG\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGAGGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGAGGACCCGCTCGATTAGTCGACTGGTAAATCGGCTAATTATTCG\n";GCAT();
HELIX<<"ACTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTA\n";GCAT();
HELIX<<"GTGGTTGAGAGAGAGAGAGAAGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTG\n";GCAT();
HELIX<<"ACTGCCCAGCGGTCAAGCGGCCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGG\n";GCAT();
HELIX<<"CCAAGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGG\n";GCAT();
HELIX<<"ACCAGTTAGCTGACTGCCCAATGAATGAACGAGAGAAGGATTCAGAGAAGGAAGGA\n";GCAT();
HELIX<<"ACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGAGGAAGCAAGTACGCGGGTA\n";GCAT();
HELIX<<"AGCGGATACGTGTATAGGCAAGTGGGTAAGCACGCATATAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTG\n";GCAT();
HELIX<<"CCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"GCGAACGATTGAGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGA\n";GCAT();
HELIX<<"GAGAAGGATCTAGAGAGAGAGAGAAGGAACTAACCGATCAACTGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGACTCG\n";GCAT();
HELIX<<"ACTGCCTGTCTGCTCGGTTAGCGGCCTGCTCGTCTGACTGTTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGTTGA\n";GCAT();
HELIX<<"GAGAGAGAGAGAGAGAAGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"CTTGATTAACCAGCTGGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGGCGA\n";GCAT();
HELIX<<"ACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGA\n";GCAT();
HELIX<<"GAGAGAGAGAGAAGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTGACTGCCCA\n";GCAT();
HELIX<<"GCGGTCAAGCGGCCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGGCCAAGCGG\n";GCAT();
HELIX<<"GTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGGACCAGTTA\n";GCAT();
HELIX<<"GCTGACTGCCCAATGAATGAACGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCGGCCAACCAAGCGGGTGGAGGAAGTAAGCGGATAAGCAGATGAGTG\n";GCAT();
HELIX<<"TACGCGTGTATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGG\n";GCAT();
HELIX<<"ACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAG\n";GCAT();
HELIX<<"CCGGATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGA\n";GCAT();
HELIX<<"GCGGTCGGGCGGCCAACCAAGCGGGTGGGCGAACGATTGAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTATTGAGAGAAGGATCTAGAGAGAGAGAGAAGGAACTA\n";GCAT();
HELIX<<"ACCGATCAACTGGCGGCCAACCAAGCGGGTGGCGTAGTTATCTAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAAGGAGAGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGCTTGATTA\n";GCAT();
HELIX<<"ACCAGCTGGCGGCATGAGCAAGTGTATGTATAGATATGTGCACGTACGAGTGCACG\n";GCAT();
HELIX<<"TGCAGCGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAATCGATTATCTGCCTGGCGG\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTAGTGGTTGAGAGAAGGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAAGGAGAGAAGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTG\n";GCAT();
HELIX<<"ACTGCCCAGCGGTCAAGCGGCCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGG\n";GCAT();
HELIX<<"CCAAGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGG\n";GCAT();
HELIX<<"ACCAGTTAGCTGACTGCCCAATGAATGAACGAAGGAGAGAAGGATTCAGAGAAGGA\n";GCAT();
HELIX<<"AGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGGCGGAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGCGTAGTGGGCGGGCGGGCGGCCAAAGTGAGTAGACGCACGTGCAAATA\n";GCAT();
HELIX<<"TATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAG\n";GCAT();
HELIX<<"ACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGG\n";GCAT();
HELIX<<"GCGGGAGAAGGAAGGAAGGAAGGAAGGACCAACCAAGCGGGTGGGTAAAGCAGGTG\n";GCAT();
HELIX<<"TCAACTAAGCGGGCGGGCGGCGTAGTGGGCGGCCAACCAAGCGGCGTAGTGGCGTA\n";GCAT();
HELIX<<"CGTACGTAGTGGCGTAGTGGGCGGCCAACCAAGCGGAGTGAGTAGACGCACGTGCA\n";GCAT();
HELIX<<"AATATATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGA\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGG\n";GCAT();
HELIX<<"ATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGG\n";GCAT();
HELIX<<"TCGGGCGGCCAACCAAGCGGGTGGGTAAAGCAGGTGGCGGCCAACCAAGCGGCGTA\n";GCAT();
HELIX<<"GTGGCGTACGTACGTAGTGGCGTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGCGGGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGGCGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGCCAAAGTAAGCGGATAAGCAGATGAGTGTACGCGTGAGCGCGTGAGCA\n";GCAT();
HELIX<<"AATAGATATCAACTAAGCGGGCGGCGTAGTGGGCGGCCAACCAAGCGGCGTAGTGG\n";GCAT();
HELIX<<"CGTACGTACGTAGTGGCGTAGTGGGCGGCCAACCAAGCGGAGTGAGTAGACGCACG\n";GCAT();
HELIX<<"TGCAAATATATAGTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGG\n";GCAT();
HELIX<<"ACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAG\n";GCAT();
HELIX<<"CCGGATAGACGAGCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGA\n";GCAT();
HELIX<<"GCGGTCGGGCGGGAGAAGGAAGGAAGGAAGGAAGGACCAACCAAGCGGGTGGGTAA\n";GCAT();
HELIX<<"AGTAAGCGGATAAGCAGATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATAGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGCGTAGTGGCGTACGTACGTAGTGGCGTAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGCGTAGTGGCGTACGTAGTTACGTACGTAGTTACGTAGTGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGCGTAGTTACGTAGTTAGTGGTTGAGAGAAGGATCTAGAGAGAGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGCGTAGTGGCGTACGTAGTTACGTAGTGGTTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTA\n";GCAT();
HELIX<<"CGTAGTTACGTAGTTACGTAGTTACGTAGTTACGTAGTTACGTAGTTACGTAGTTA\n";GCAT();
HELIX<<"CGTAGTTAGTGGTTGAGAGAGAGAGAGAGAGAGAGAAGGAACTAACCGATCAACTG\n";GCAT();
HELIX<<"GAGAGAGAAGGAAGGACCAACCAAGCGGGTGGACCAGTTACCTGGCGGACTAACCG\n";GCAT();
HELIX<<"ACCAGTTAGCGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAATCGATTATCTGCCTG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTACGTACGTAGTTACGTACGTA\n";GCAT();
HELIX<<"GTTACGTAGTGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGAATAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAAATACGTACGTAGTTACGTAGTGG\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGCCTAGCGGTACGTGTGAGTAGATAAGTGCACG\n";GCAT();
HELIX<<"AGCGCGTGAATACACGGCGGCACGAGTGCATGCCGGTCGAGCGGGATATGTGCACG\n";GCAT();
HELIX<<"TACGAGTGCACGTGCAGCGGCCTACGTACGTAGTTACGTAGTGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAATAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAAATACGTACGTAGTTACGTACGTAGTTACGTACGTAGTTACGTAGTGG\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGATTAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAATTACGTACGTA\n";GCAT();
HELIX<<"GTTACGTAGTGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGCCTAGCGGCGTGGGCAAGCATACGGCGGGATATGTGCACG\n";GCAT();
HELIX<<"TACGAGTGCACGTGCAGCGGTATGAGCAGGTAGGTAGCGGAGTAAGCGGATAAGCA\n";GCAT();
HELIX<<"GATGAGTGTACGCGTGGCGGCGTGGGCAAGTGGCGGGATGAATAGGTAGGTAAATA\n";GCAT();
HELIX<<"TATGAGCAGATAAATGGCGGTACGAATATGTGCACGAACGAGTGGCGGAACGAATA\n";GCAT();
HELIX<<"GGTGAGTGGCGGAGTGAGTAGACGCACGTGCAAATAGCGATACGACGACTGAGCGG\n";GCAT();
HELIX<<"CCTACGTACGTAGTTACGTAGTGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"CGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGATTAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAATTACGTACGTAGTTACGTACGTAGTTACGTAGTGGTTGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGACATG\n";GCAT();
HELIX<<"AGCAAGTGTATGTATAGATATGTGCACGTACGAGTGCACGTGCAGCGAACGATTGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAATCG\n";GCAT();
HELIX<<"ATTATCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGTACACGCGCACGAGTGTACGTACGGCGG\n";GCAT();
HELIX<<"AGTGGATACGTGAGTGCACGGCGGCGTGAATAGCGGAACGAATAGATACGTGAGCA\n";GCAT();
HELIX<<"GATATGTGAGTGTGTAGCGGCGTAGTGGTTGAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTA\n";GCAT();
HELIX<<"ACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAATCGACCAGTTAGTAA\n";GCAT();
HELIX<<"ATTGACTGCCTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTAGCGGGCGGGCGGGCGGGCGGGGTGAATAGCGG\n";GCAT();
HELIX<<"TGCAAATATGTGGCGGTATGAGCGGATACGTGGCGGCGTGAATAGCGGAGTAAGCG\n";GCAT();
HELIX<<"GATAAGCAGATGAGTGTACGCGTGGCGGCGTGGGCAAGTGGCGGAACGAATAGGTG\n";GCAT();
HELIX<<"AGTGGCGGAGTGAGTAGACGCACGTGCAAATAGCGATACGACGAGCGGAGCAGATA\n";GCAT();
HELIX<<"CGTGAATAGCGGCGTGGGCAAGTGGCGGAGCGAACGCGTGAGCACATGAGTGGCGG\n";GCAT();
HELIX<<"GGTGAGCACACGAGTGAACGCGTGAATACACGTGCATTAACGTACGTAGTTACGTA\n";GCAT();
HELIX<<"GTGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGTACAAGTGGATACGTG\n";GCAT();
HELIX<<"AGTGCACGGCGGCGTACGTAATAGTGCACGTACGTAATAGGCGGAATACACGGCGG\n";GCAT();
HELIX<<"CGTACGTAATAGGATACGTACGTAATAGGCGGGATAAATATATGTGTAGCGGGCGG\n";GCAT();
HELIX<<"CGTAGTGGTTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGAAGGATTCAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCG\n";GCAT();
HELIX<<"CCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAATCGGCCAACCG\n";GCAT();
HELIX<<"CTCGGCGGTCTGTTCGACTGCTCGTATGACCGGTTACCTGTTCGAGTAACCGGTTA\n";GCAT();
HELIX<<"ACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTATTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTG\n";GCAT();
HELIX<<"CCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGA\n";GCAT();
HELIX<<"AGGAGCTGATTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGAAGGAAGGATTCAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTA\n";GCAT();
HELIX<<"ACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGAATCG\n";GCAT();
HELIX<<"ACCAGTTAGCGGCTAACTAAGCGGTCTGTTCGACTGCTCGTATGACCGGTTACCTG\n";GCAT();
HELIX<<"TTCGAGTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTA\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGAGGAAGGAAGGAAGGAACCAGTTGGCGGGCGAGCGATCTGTTCGACTG\n";GCAT();
HELIX<<"CTCGTATGACCGGTTACCTGTTCGAGTAACCGGTTAACCAGTTGACTGTTCGCCTG\n";GCAT();
HELIX<<"ACCGCCTGACCAATTAGTTAGCGGTCAATCAAGCGGATAGGATAATAGACGAGCGG\n";GCAT();
HELIX<<"CCTACCTAGCGGGCGATCTGTTCGACTGCTCGTATGACCGGTTACCTGTTCGAGTA\n";GCAT();
HELIX<<"ACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTAGCGGTCAA\n";GCAT();
HELIX<<"TCAAGCGGATAGGTTAATAGACGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCG\n";GCAT();
HELIX<<"CCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGATTCAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"ACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGCGTA\n";GCAT();
HELIX<<"GTGGCGTACGTAGTTACGTACGTAGTTACGTACGTAGTTAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGCGCGGGTAAGTGAGCGTACGAGTGGCGGCACGTGTG\n";GCAT();
HELIX<<"GATAGCGGCGTGGGCAAGCATACGGCGGGATATGTGCACGTACGAGTGCACGTGCA\n";GCAT();
HELIX<<"GCGGAGCGAATGAGCGAGCAGATAGCGGCGTGAATAGCGGAGTAAGCGGATAAGCA\n";GCAT();
HELIX<<"GATGAGTGTACGCGTGGCGGCGTGGGCAAGTGGCGGAACGAATAGGTGAGTGGCGG\n";GCAT();
HELIX<<"AGTGAGTAGACGCACGTGCAAATAGCGATACGACGAGTAACGTACGTAGTTACGTA\n";GCAT();
HELIX<<"CGTAGTTACGTACGTAGTTACGTAGTGGGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCG\n";GCAT();
HELIX<<"CCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGTACACGCGCACGAGTGTACGTACGGCGGAGTGGATACGTG\n";GCAT();
HELIX<<"AGTGCACGGCGGCGTGAATAGCGGAGTGCGCAAGCACGTGTGTAGCGGCGTAGTGG\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGAGGAAGGAAGGAAGGAAGGAATCGACCAGTTAGTAAACCAATTGGTTA\n";GCAT();
HELIX<<"ATTACTCGACTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTG\n";GCAT();
HELIX<<"ACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGAAGGAATCGACCA\n";GCAT();
HELIX<<"GTTAGTAAATTGACTGCCTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTA\n";GCAT();
HELIX<<"ACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"CTCGACTGCCTGTCTGCTCGGTTAGCGGACAATCGGTTGAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTG\n";GCAT();
HELIX<<"ATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGAGGAAGGAAGGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCGTCTGCCTGATTAACTAACCG\n";GCAT();
HELIX<<"CCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGAAGGAAGGATTTGGCCAACCA\n";GCAT();
HELIX<<"GCTAACTGGCGGGCGAGCGATCTGTTCGACTGCTCGTATGACCGGTTACCTGTTCG\n";GCAT();
HELIX<<"AGTAACCGGTTAACCAGTTGACTGTTCGCCTGACCGCCTGACCAATTAGTTAGCGG\n";GCAT();
HELIX<<"ACGGTCAAGCGGATAGTGCAATAGACGAGCGGGTAGGTAGGCGGGCGATCTGTTCG\n";GCAT();
HELIX<<"ACTGCTCGTATGACCGGTTACCTGTTCGAGTAACCGGTTAACCAGTTGACTGTTCG\n";GCAT();
HELIX<<"CCTGACCGCCTGACCAATTAGTTAGCGGACGGTCAAGCGGATAGTCCAATAGACGA\n";GCAT();
HELIX<<"ACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGAGGAAGGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTACGTAGTGGTTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAACCAGTTG\n";GCAT();
HELIX<<"GCGGGCGAACGGAGCAAGTACGCGGGTAAGCGGATACGTGTATAGGCAAGTGGGTA\n";GCAT();
HELIX<<"AGCACGCAGCGAACGAACGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGGTGGAGGATTCAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGAATCG\n";GCAT();
HELIX<<"ATTATCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTACGTACGTA\n";GCAT();
HELIX<<"GTTACGTACGTAGTTAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGTATGAGCGCACGGATAAGCAGATAAATGACGG\n";GCAT();
HELIX<<"ACGGACGGGCGGAACGAGCGGATAGATAAATACGTGGCGGAGCAAGTACGCGGGTA\n";GCAT();
HELIX<<"AGCGGATACGTGGCGGGGCAAGTGGGTAAGCACGCAGCGGAGCAGATACGTGAATA\n";GCAT();
HELIX<<"GCGGAGTGAGTAGACGCACGTGCAAATAGCGATACGACGAACGGCGTACGTAGTTA\n";GCAT();
HELIX<<"CGTAGTGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGAAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGCGCGGGTA\n";GCAT();
HELIX<<"AGTGAGCGTACGAGTGGCGGAGTGGATAAGCGGACGGGTAAGTGGCGGTATGCACG\n";GCAT();
HELIX<<"AGCACGTGAGTGGCGGAGCGAACGAACGAGTGTACGTACGGCGGCGTGAATAGCGG\n";GCAT();
HELIX<<"CGTGGGCAAGTGGCGGAGCGAACGCGTGAGCACATGAGTGGCGGGGTGAGCACACG\n";GCAT();
HELIX<<"AGTGAACGCGTGAATACACGTGCACGTACGTAGTTACGTAGTGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAGCGGATAGGTGGCGGCACGTGTGGATAGCGGCGTGGGCAAGCA\n";GCAT();
HELIX<<"TACGGCGGGATATGTGCACGTACGAGTGCACGTGCAGCGGAGCGAATGAGCGAGCA\n";GCAT();
HELIX<<"GATAGCGGCGTGAATAGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGGCGG\n";GCAT();
HELIX<<"CGTGGGCAAGTGGCGGAACGAATAGGTGAGTGGCGGAGTGAGTAGACGCACGTGCA\n";GCAT();
HELIX<<"AATAGCGATACGACGAGTAACGTACGTAGTTACGTACGTAGTTACGTAGTGGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGGAAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGTACACGCGCACGAGTGTACGTACG\n";GCAT();
HELIX<<"GCGGAGTGGATACGTGAGTGCACGGCGGCGTGAATAGCGGAGTGCGCAAGCACGTG\n";GCAT();
HELIX<<"TGTAGCGGGCGGCGTAGTGGTTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGAATCGACCAGTTAGTAA\n";GCAT();
HELIX<<"ACCAATTGGTTAATTACTCGACTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGAATCG\n";GCAT();
HELIX<<"ACCAGTTAGTAAATTGACTGCCTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAAGGACTCG\n";GCAT();
HELIX<<"ACTGCCTGTCTGCTCGGTTAGCGGACAATCGGTCGGTTGAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGATCTA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGAATCGATTATCTGCCTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGCGTAGTGGCGTACGTAGTTACGTACGTAGTTACGTACGTAGTTA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGTACGTGTG\n";GCAT();
HELIX<<"AACGAACGAGTGTACGTACGGATGTGTGGGTAGGTATGCAGCGGAGCAAGTACGCG\n";GCAT();
HELIX<<"GGTAAGCGGATACGTGAGTGGGTGGCGGGGCAAGTGGGTAAGCACGCAGCGGAGCA\n";GCAT();
HELIX<<"GATACGTGAATAGCGGTACGAATATGTGCACGAACGAGTGGCGGAACGAATAGGTG\n";GCAT();
HELIX<<"AGTGGCGGAGTGAGTAGACGCACGTGCAAATAGCGATACGACGACGTACGTAGTTA\n";GCAT();
HELIX<<"CGTAGTGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGTACACGCGCACGAGTGTACGTACGGCGGAGTGGATACGTGAGTG\n";GCAT();
HELIX<<"CACGGCGGCGTGAATAGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGGCGG\n";GCAT();
HELIX<<"AGTGAGTAGACGCACGTGCAAATAGCGATACGACGAGCGGGATAAATATATGTGTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTACGTACGTAGTTACGTAGTGGTTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACCG\n";GCAT();
HELIX<<"TCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"ATCGACCAGTTAGTAAACCAATTGGTTAATTACTCGACTGGCGAACGATTGAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"ACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAATCGACCAGTTAGTAAATTGACTGCCTGGCGAACGATTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"CGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGTACA\n";GCAT();
HELIX<<"GATAAATATATGGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTGAGCAGATA\n";GCAT();
HELIX<<"AATGGCGGCGTGGGCAAGTGGCGGTACGAATATGTGCACGAACGAGTGGCGGAACG\n";GCAT();
HELIX<<"AATAGGTGAGTGGCGGAGTGAGTAGACGCACGTGCAAATAGCGATACGACGAGTAA\n";GCAT();
HELIX<<"GCGGCGCGGGTAAGTGAGCGTACGAGTGGCGGTATGAGCGAGCACGTGGTAATGTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTACGTACGTAGTTACGTAGTGGTTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAAGTAAGCGGATAAGCAGATGAGTGTACGCGTGGCGAACGATTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"AGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGCGTAGTGGCGTACGTAGTTA\n";GCAT();
HELIX<<"CGTACGTAGTTACGTACGTAGTTAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAGTGAGTAGACGCACGTGCAAATAGCGGAGTAAGCGGATAAGCA\n";GCAT();
HELIX<<"GATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATAGCGGAACGAATAAGTACGCG\n";GCAT();
HELIX<<"GGTAAGTGCGTGAGTGGTAAGCGGCGCGGGTAAGTGAGCGTACGAGTGGCGGAACG\n";GCAT();
HELIX<<"AATAAGTACGCGAGCAGGTAAGTGGCGGAGCGGATAGGTGGCGGCACGTGTGGATA\n";GCAT();
HELIX<<"GCGGCGTGGGCAAGTGGCGGCGTACGTAGTTACGTAGTGGGCGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGTACGAATATGTGCACGAACGAGTGGCGGAACGAATAGGTGAGTGGCGG\n";GCAT();
HELIX<<"TATGGGCAAGCAAACGGGCAGCGGGGCAAGCGTACGGCGGAGTAAGCGGATAAGCA\n";GCAT();
HELIX<<"GATGAGTGTACGCGTGAGTGGGTGGCGGAGCAGATACGTGAATAGCGGCGTGGGCA\n";GCAT();
HELIX<<"AGTGGCGGAGCGAACGCGTGAGCACATGAGTGGCGGGGTGAGCACACGAGTGAACG\n";GCAT();
HELIX<<"CGTGAATACACGTGCAGTAACGTACGTAGTTACGTACGTAGTTACGTACGTAGTTA\n";GCAT();
HELIX<<"CGTAGTGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGAAGGACCAACCAAGCGGCGTAGTGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGTACACGCGCACGAGTG\n";GCAT();
HELIX<<"TACGTACGGCGGAGTGGATACGTGAGTGCACGGCGGCGTGAATAGCGGAGTGCGCA\n";GCAT();
HELIX<<"AGCACGTGTGTACGTACGTAGTTACGTACGTAGTTACGTACGTAGTTACGTAGTGG\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAA\n";GCAT();
HELIX<<"CCAAGCGGACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGAGGAATCGACCAGTTAGTAAATTGACTGCCTGGCGAACGATTGAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGGTGGAGGACTCGACTGCCTGTCTGCTCGGTTA\n";GCAT();
HELIX<<"GCGGCCAGCTGGCCGGACAACCAGCTGGCCGGTTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"CGTAGTTACGTAGTTACGTAGTTACGTAGTTAGTGGTTGAGAGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGA\n";GCAT();
HELIX<<"GAGAGAGAGAGAAGGAGTTGATTACTCGGCGGGCGAACCAGTTAGCTGACTGCCCA\n";GCAT();
HELIX<<"GCGGTCAAGCGGCCGGTTGAGCGGACCAGTTAGCTGACTGCCCAGCGGCCAAGCGG\n";GCAT();
HELIX<<"GTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCGTTGAGCGGACCAGTTA\n";GCAT();
HELIX<<"GCTGACTGCCCAATGAATGAACGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCGGCCAACCAAGCGGGTGGCGTAGTTACTTGATTAACCAGCTGGCGG\n";GCAT();
HELIX<<"AGCAAGTACGCGGGTAAGCGGATACGTGTATAGGCAAGTGGGTAAGCACGCATATA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGTTCGACTGCCTGTTTGGCGACTGGACGAGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGTTCGACTGCCTGGTTGACCAGCTAGCTAGCGAATAGCCGGATAGACGA\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACCAGTTAGCTGACTGCCCAGCGGATGAGCGGTCGGGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGACCAACCAAGCGGGTGGGCGAGATATGTGCACGTACG\n";GCAT();
HELIX<<"AGTGCACGTGCAGCGGAGTGAGTAGACGCACGTGCAAATAACGATTCAATTAGTTG\n";GCAT();
HELIX<<"TTCGCCTGCTCGACTGACCGACTAGCGGGGCAAGTGGGTAAGCACGCAGCGAAGTG\n";GCAT();
HELIX<<"AGTAGACGCACGTGCAAATAGTAAGGCAAGTGGGTAAGCACGCAGTAAATCGTATA\n";GCAT();
HELIX<<"TTCGCCTGCTCGGCGAACGAACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTATTGAGAGAAGGAAGGAGAGAAGGAAGGAACTGGTTAATCGAATGAACG\n";GCAT();
HELIX<<"AGCGCGTGCCGGTTAGGCGAACTAACCGATCAACTGGCAAGCGGACCAGTTAGCTG\n";GCAT();
HELIX<<"ACTGCCCAGCGGATGAGCGGTCGGGCAAGCGGACTAACCGGTTAACCAGTTGACTG\n";GCAT();
HELIX<<"TTCGCCTGACCGCCTGACCAATTAGTTATACAACCAGTTAGCTGACTGCCCATGTA\n";GCAT();
HELIX<<"ACGATTGAGAGAAGGATCTAGAGAGAGAGAGAGAGAGAGAGAGAAGGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCGGCCAACCAAGCGGGTGGCGTAGTTACTTGATTAACCAGCTGGCGG\n";GCAT();
HELIX<<"AATGAACGAGCGCGTGGCGAACGATTCAATCGATTATCTGCCTGCCAACCAAATCG\n";GCAT();
HELIX<<"GCCAACCGCTCGGCGAATAGGCGAATAGATGAATAGGTGAATAGATGAATAGGTGA\n";GCAT();
HELIX<<"ATAGATGAATAGGTGAATAGACAAATAGATGAATAGACAAATAGATGAATAGATGA\n";GCAT();
HELIX<<"ATAGACAAATAGATGAATAGACAAATAGACAAATAGATAAATAGACAAATAGATAA\n";GCAT();
HELIX<<"ATAGACAAATAGACGAATAGACGATTGATCTAGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAGAGACCAACCAAGCGGGTGGCTTGATTAACCAGCTGGCGG\n";GCAT();
HELIX<<"GGCAAGCGCACGCATGAGTGTACGCGTGTATAAGTGAGTAGACGCACGTGCAAATA\n";GCAT();
HELIX<<"GCGAGATATGTGCACGTACGAGTGCACGTGCAGCGGAGTGAGTAGACGCACGTGCA\n";GCAT();
HELIX<<"AATAACGATTCAACCAGTTACCTGGCGGCTCAACCGCCCGTCAAATAGGCGAATAG\n";GCAT();
HELIX<<"ATGAATAGACAAATAGACAAATAGGTGAATAGATGAATAGACAAATAGACAAATAG\n";GCAT();
HELIX<<"ATGAATAGACAAATAGGTGAATAGACAAATAGATGAATAGATGAATAGACGAATAG\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGACCAGTTGTTCGCCTGCTCGACTGACCGACTAGCGGTGCAAATATGTGTATA\n";GCAT();
HELIX<<"AGCGCACGAGTGTATAGATAAATACGTGTATAAGCGTGTGCGTGGGCAAATACACG\n";GCAT();
HELIX<<"AGCACACAAGTGGGTGTATACGTGAATATATACACGAGTGAGCGGGTGTATACGTG\n";GCAT();
HELIX<<"GGCAAGCATACGGCGAAGTGAGTAGACGCACGTGCAAATAGTAAGGCAAGTGGGTA\n";GCAT();
HELIX<<"AGCACGCAGTAAATCGTATATTCGCCTGCTCGGCGAACGAACGATTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGATTAGTTG\n";GCAT();
HELIX<<"TTCGCCTGCTCGACTGACCGACTAGCGGTGCAAATATGTGTATAAGTATGTGTACG\n";GCAT();
HELIX<<"CGTGTATAAGCAAGTAAGTAAGTGGGTGAGCAAGCGCGTGAGTGGGTATGCATATA\n";GCAT();
HELIX<<"GGTGAGTGTACGAGCATACGCGTGGCGAAGTGAGTAGACGCACGTGCAAATAGTAA\n";GCAT();
HELIX<<"AGTAAGCGGATAAGCAGATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATAGTAA\n";GCAT();
HELIX<<"ATCGTATATTCGCCTGCTCGGCGAACGAACGATTGAACCAGTTACCTGGCGGGTCG\n";GCAT();
HELIX<<"ACCGACTATCAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGATAGGCGAATAGACAAATAGATGAATAGACAAATAGATGAATAG\n";GCAT();
HELIX<<"ACAAATAGATGAATAGATGAATAGATAAATAGATGAATAGACGAATAGACAAATAG\n";GCAT();
HELIX<<"GCGAATAGATGAATAGATGAATAGATGAATAGATGAATAGATGAATAGATGAATAG\n";GCAT();
HELIX<<"ACAAATAGATAAATAGACAAATAGACGAATAGTTGAGTCGATTAATTAGCTAGCGG\n";GCAT();
HELIX<<"GTCGACCGGTTAATTGTCAAGTCGACCGACTATTGAGCTGATTATTCAACCAGTTA\n";GCAT();
HELIX<<"CCTGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGATCGCTCGTCTGGTTAATCGGCCATTGATTCGCCTGCTCGACCAGTTAATTG\n";GCAT();
HELIX<<"GCGGCTCAATTATTTGACCAACTGTTGAATTGACTGCCTGGCTAACCAGTTAACTG\n";GCAT();
HELIX<<"GCGATGCAAATATGTGTATAAGCGCACGAGTGTATAGATAAATACGTGTATAAGCG\n";GCAT();
HELIX<<"TGTGCGTGGGCAAATACACGAGCACACAAGTGGGTGTATACGTGAATATATACACG\n";GCAT();
HELIX<<"AGTGAGCGGGTGTATACGTGGGCAAGCATACGGCAACTCAATTATTTGACCAACTG\n";GCAT();
HELIX<<"ACGATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGACCAGTTGGCGATGCAAATATGTGTATAAGCGCACGAGTGTATAGATA\n";GCAT();
HELIX<<"AATACGTGTATAAGCGTGTGCGTGGGCAAATACACGAGCACACAAGTGGGTGTATA\n";GCAT();
HELIX<<"CGTGAATATATACACGAGTGAGCGGGTGTATACGTGGGCAAGCATACGGTAAGTTG\n";GCAT();
HELIX<<"ACCGACCAGCTAGCGAACGAACGAGTCGACCGGTTAATTGTCAACTCAACCGCCCG\n";GCAT();
HELIX<<"TTGAATCGCTCGTCTGGTTAATCGGCCATCAAGTCGACCGACTATTGAACCAGTTA\n";GCAT();
HELIX<<"CCTGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGATCAGCTAATTAGTTAATCATCAAATAGGCGAATAGACAAATAGATGAATAG\n";GCAT();
HELIX<<"ATGAATAGACAAATAGACAAATAGGTGAATAGATGAATAGACGAATAGACAAATAG\n";GCAT();
HELIX<<"GCGAATAGACAAATAGATGAATAGATGAATAGACAAATAGACAAATAGGTGAATAG\n";GCAT();
HELIX<<"ATGAATAGACGAATAGTTGAACCAGTTACCTGGCGGTTTGGCCAACCGCCCGTCAA\n";GCAT();
HELIX<<"ATCAGCTAATTAGTTAATCAATGACTCAACCGCCCGTTGAACCAGTTACCTGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGATCA\n";GCAT();
HELIX<<"GCTATCTGGTTAATCATCAAATAGGCGAATAGACAAATAGATGAATAGACAAATAG\n";GCAT();
HELIX<<"GTGAATAGATGAATAGACGAATAGACAAATAGGCGAATAGACAAATAGATGAATAG\n";GCAT();
HELIX<<"ATGAATAGATAAATAGATGAATAGACGAATAGACAAATAGGCGAATAGATGAATAG\n";GCAT();
HELIX<<"ATAAATAGACAAATAGGTGAATAGATGAATAGACGAATAGTTGAACCAGTTACCTG\n";GCAT();
HELIX<<"GCGGCTCAACCGACTATCAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGACCAACCAAGCGGGTGGATCAGCTAATTAGTTAATCAGTGAATCAGCTAATTA\n";GCAT();
HELIX<<"GTTAATCAATGAATCAGCTATCTGGTTAATCAGTGAATCAGCTATCTGGTTAATCA\n";GCAT();
HELIX<<"ATGAATCAGCTAATTAGTTAATCAGTGAATCAGCTATCTGGTTAATCATTGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGCTCAACCGACTAACTATCAACTCAACCGACTAACAAATCAGCTA\n";GCAT();
HELIX<<"ATTAGTTAATCATTGAACCAGTTACCTGGCGGCTCAACCGACTAACTAACTATCAA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"ATCAGCTAATTAGTTAATCAGTGAATCAGCTATCTGGTTAATCAGTGAATCAGCTA\n";GCAT();
HELIX<<"ATTAGTTAATCAGTGATTTGGCCAACCGCCCGTTGATTTGGCCAACCAGCTAACTG\n";GCAT();
HELIX<<"GCGAATCGCTCGTCTGGTTAATCGGCCACCAACTCAATTATTTGACCAACTGGTAA\n";GCAT();
HELIX<<"GCTAACTGGTTAATTGCCTGGCCAGCGAACGAACGATTCAACCAGTTACCTGGCGG\n";GCAT();
HELIX<<"ATCAACTGCTCGCCCGGCTAATTACCCGTCAAGTCGACCGACTATTGAGTGGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGGTTGATTA\n";GCAT();
HELIX<<"CTCGGCGAACCAGTTACCTGGCGGTTTGGCCAACCGATCGATCATCAATTTGGCCA\n";GCAT();
HELIX<<"ACCGCCCGTTGATTTGGCCAACCGATCGATCACTAATCAAGTCGACCGACTATTGA\n";GCAT();
HELIX<<"TTTGGCCAACCGATCGATCAACAAACAAACGATTCAATCGGCCAACCGCTCGGCGG\n";GCAT();
HELIX<<"ATCAACCGCCCGATTATTTGTCAACTCAATTATTTGACCAACTGTACAATCGCTCG\n";GCAT();
HELIX<<"TCTGGTTAATCGGCCATGTATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGACCAACCAAGCGGGTGGACCAGTTACCTGGCGGCCTGGCCATTTGACCG\n";GCAT();
HELIX<<"ATCGATCATCAAATCAGCTAATTAGTTAATCAATGATTTGGCCAACCGATCGATCA\n";GCAT();
HELIX<<"ATGAATCAGCTAATTAGTTAATCATTGAATCAACTGCTCGCCCGGCTAATTACCCG\n";GCAT();
HELIX<<"ATGATCAAGCGAATCAACCGCCCGATTATTTGTCAATCAACTCAACCGACTATTAA\n";GCAT();
HELIX<<"CCCGATTATTTGGCGAATCAGCTAATTAGTTAATCAGCAAATCAGCTATCTGGTTA\n";GCAT();
HELIX<<"ATCAACAATTTGGCCAACCGATCGATCAACGACTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGGCGAATCAACCGCCCGATTA\n";GCAT();
HELIX<<"TTTGTCAATCAACTCAACCGACTAACTATTAACCCGATTATTTGGCGAATCAGCTA\n";GCAT();
HELIX<<"ATTAGTTAATCAGCAAATCAGCTATCTGGTTAATCAACAACCTGGCCATTTGACCG\n";GCAT();
HELIX<<"ATCGATCAACGACTGAGCGAATCAACCGCCCGATTATTTGTCAATCAACTCAACCG\n";GCAT();
HELIX<<"ACTAACTAACTATTAACCCGATTATTTGGCGAATCAGCTAATTAGTTAATCAGCAA\n";GCAT();
HELIX<<"ATCAGCTATCTGGTTAATCAACAACCTGGCCATTTGACCGATCGATCAACGAATGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"CCCGATTATTTGGCGAATCAGCTAATTAGTTAATCAGCAAATCAGCTATCTGGTTA\n";GCAT();
HELIX<<"ATCAACAATTTGGCCAACCGATCGATCAACGACTGAGTCGACCGACTAACGAACGA\n";GCAT();
HELIX<<"ACGATTGAATCGCTCGTCTGGTTAATCGGCCAATGAATGATTGAAATGAACGAGCG\n";GCAT();
HELIX<<"CGTGGCGAACGATTGATCTATGCAAATATGTGTATAAGTATGTGTACGCGTGTATA\n";GCAT();
HELIX<<"AGCAAGTAAGTAAGTGGGTGAGCAAGCGCGTGAGTGGGTATGCATATAGGTGAGTG\n";GCAT();
HELIX<<"TACGAGCATACGCGTGCCAACCAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGACCAACCAAGCGGGTGGATCGGCCAACCGCTCGGCGAATCAACTGCTCG\n";GCAT();
HELIX<<"CCCGGCTAATTACCCGACGATTGATCTATCTATTTGGCCAACCAGCTAACTGGCGA\n";GCAT();
HELIX<<"ACGGGTCGACCGGTTAATTGACGATTGATGCAAATATGTGTATAAGCGCACGAGTG\n";GCAT();
HELIX<<"TATAGATAAATACGTGTATAAGCGTGTGCGTGGGCAAATACACGAGCACACAAGTG\n";GCAT();
HELIX<<"GGTGTATACGTGAATATATACACGAGTGAGCGGGTGTATACGTGGGCAAGCATACG\n";GCAT();
HELIX<<"GTAAATCGGCTAATTATTCGACTGGCGAACGATTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGACCAACCAAGCGGGTGGTGCAAATATGTGTATAAGTA\n";GCAT();
HELIX<<"TGTGTACGCGTGTATAAGCAAGTAAGTAAGTGGGTGAGCAAGCGCGTGAGTGGGTA\n";GCAT();
HELIX<<"TGCATATAGGTGAGTGTACGAGCATACGCGTGGTAAATCGGCTAATTATTCGACTG\n";GCAT();
HELIX<<"GCGAACGATTGATCTAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGA\n";GCAT();
HELIX<<"GAGAGAGAGAGAGAGAGAGAATAAGTGAGAGAGAGAGCGGAGGAAACGGGTAAGCG\n";GCAT();
HELIX<<"TACGTACGAGCAAACGGCGGGACGAGCGCGTGAGTAAGCGGATAGCGGGACGAGCG\n";GCAT();
HELIX<<"CGTGGATGAGCAAATGGGCACGTGGCGGTATGAATACACGGGTGTACGCTGAGAGA\n";GCAT();
HELIX<<"GAGAGAGAGCGGGCGGGCGGGCGGAGCGAGCAAGTGAGTGAGTGACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAGCGAGCAAGCAAGTGAGTGAGTGACGGGAGAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGAGCGCACGCACGAATGGGCAACGGGAGAGCGGGCGGGCGGGCGGAGCGTATG\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGAGCGTATGAACAAACAAACAAACAAACA\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGGACGAGCGAGTAACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGACGAGCGGATAAATGACGGGAGAGCGGGCGGGCGGGCGGGACGAGCG\n";GCAT();
HELIX<<"GATAAATGACAAAGTGCGTGGGCAACGGGAGAGCGGGCGGGCGGGCGGGACGAGCA\n";GCAT();
HELIX<<"GATGGATGACGGGAGAGCGGGCGGGCGGGCGGGACGGGTAAATAAATACGCGACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGGACGGGTATGTGCACGCGCGACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGACGAATAGATGGATGACGGGAGAGCGGGCGGGCGGGCGGGACGAATA\n";GCAT();
HELIX<<"GATAAACAACGGGAGAGCGGGCGGGCGGGCGGAACGGGTAAGCGGATAAACAACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGAACGGGTAAGCGGATAAACAACAAAGTGTACGCGTG\n";GCAT();
HELIX<<"ACGGGAGAGCGGGCGGGCGGGCGGAACGGGTAAGCGTACGGGCAACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAACGGGTATGTGGATAAACAACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AACGGGTATGTGGATAAACAACAAAGTGCGTGGGCAACGGGAGAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGAACGCACGCACGAGCGAGCGAACGAACAACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AACGCACGAGCGTACGGGCAACGGGAGAGCGGGCGGGCGGGCGGAACGCACGCACG\n";GCAT();
HELIX<<"AGCGAGCGAACGAACAACGGGAGAGCGGGCGGGCGGGCGGAACGCACGTGTGGATA\n";GCAT();
HELIX<<"AACGGGCAACGGGAGAGCGGGCGGGCGGGCGGAACGCACGTGTGGATAAACGGGCA\n";GCAT();
HELIX<<"ACAAAGTGCGTGGGCAACGGGAGAGCGGGCGGGCGGGCGGAGTGAGTGAGTGACAA\n";GCAT();
HELIX<<"TGCAAATATATGACGGGAGAGCGGGCGGGCGGGCGGGATGGGTACACGGACGGACG\n";GCAT();
HELIX<<"GACGGACGGACGACGGGAGAGCGGGCGGGCGGGCGGAATGGGTAAGCACGCGCGCG\n";GCAT();
HELIX<<"ACGGGAGAGCGGGCGGGCGGGCGGAATGGGTATGTGCACGCGCGCGCGACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGAACAAGCGCGCGAATATATGACGGGAGAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGAACAAGCGTGCAAATAACGGGAGAGCGGGCGGGCGGGCGGAACAAGTGCACG\n";GCAT();
HELIX<<"ACAATACGCGCGGGTAAATAAATATACGGGCAACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AACAAGTGCACGCGCGGGTAAATACGCGACGGGAGAGCGGGCGGGCGGGCGGAACA\n";GCAT();
HELIX<<"GGTAAATAGATAAACAACGGGAGAGCGGGCGGGCGGGCGGAACAGGTATGTGGATA\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGAACACACGTGTGGATAAACGGGCAACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGAATAAATAAATAGATGGATGACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGAATAAATAAATAAATAGATGGATGACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"AATATGTGAACGGGCAACGGGAGAGCGGGCGGGCGGGCGGAATATGTGAACGGGCA\n";GCAT();
HELIX<<"ACAAAGTGCGTGGGCAACGGGAGAGCGGGCGGGCGGGCGGAATATATGTATGTATG\n";GCAT();
HELIX<<"ACGGGAGAGCGGGCGGGCGGGCGGAATATATGACAAAGTGCGTGGGCAGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGCGCGAGCGAGTAACGGGAGAGCGGGCGGGCGGGCGGCGCGGGTA\n";GCAT();
HELIX<<"AATACGCGACGGGAGAGCGGGCGGGCGGGCGGCGCGAATATATGACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGCGCGAATATATGAGCAAGTGACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"TGCGTGTGGATAAACGAACAAACAAACAACGGGAGAGCGGGCGGGCGGGCGGCACG\n";GCAT();
HELIX<<"AGCGAACAAACAAACAACGGGAGAGCGGGCGGGCGGGCGGCACGAGCACGCGACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGTACGGGTAAATATACGGGCAACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGTACGAATAAACGAACAACGGGAGAGCGGGCGGGCGGGCGGTACGCGCG\n";GCAT();
HELIX<<"GGTAAGCGCGTGTACGACGGGAGAGCGGGCGGGCGGGCGGTACGCGCGGGTAAGCG\n";GCAT();
HELIX<<"CGTGCGTGACGGGAGAGCGGGCGGGCGGGCGGTACGCGCGGGTAAATAAATATACG\n";GCAT();
HELIX<<"GGCAACGGGAGAGCGGGCGGGCGGGCGGTACGTATGAGCGAGCGCGCGACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGTACGTATGAGCATACGGGCAACGGGAGAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGTACGTATGAATAAATATACGGGCAACGGGAGAGCGGGCGGGCGGGCGGCGTG\n";GCAT();
HELIX<<"GGCATGTGGATAAACAACGGGAGAGCGGGCGGGCGGGCGGCGTGGGCATATGAGCG\n";GCAT();
HELIX<<"AACGAACAACGGGAGAGCGGGCGGGCGGGCGGCGTGGGCATATGAGCGAACGAACA\n";GCAT();
HELIX<<"AGTGACGGGAGAGCGGGCGGGCGGGCGGCGTGGGCATATGAGCGCGCGAGTGACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGCGTGGGCATATGAGCGCGCGCGCGACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGTGTGAATGAATGGGCAACGGGAGAGCGGGCGGGCGGGCGGTGTG\n";GCAT();
HELIX<<"CACGAACAAACAAACAACGGGAGAGCGGGCGGGCGGGCGGCATGCACGAATAGATA\n";GCAT();
HELIX<<"AACAACGGGAGAGCGGGCGGGCGGGCGGTATGGGCAAGCGAACGAACAACGGGAGA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGTATGGGCAAGCGAACGAACAACAAAGTGCGTGGGCAACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGTATGGGCAAGCGAGTAACAAAGTGCGTGGGCAACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGTATGGGCAAGCGAGTAAGTAACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGTATGGGCAAGCGAGTAAGTAAGTAACGGGAGAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"TATGGGCAAGCGCGCGACGGGAGAGCGGGCGGGCGGGCGGCACAACAACACATATG\n";GCAT();
HELIX<<"AGCGCGCGACGGGAGAGCGGGCGGGCGGGCGGCACAAGCGAGTAACGGGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGCACAAGCGAGTAAGTAACGGGAGAGCGGGCGGGCGGGCGGCACA\n";GCAT();
HELIX<<"AGCGAGTAAGTAAGTAACGGGAGAGCGGGCGGGCGGGCGGCACAAGCGCGCGACGG\n";GCAT();
HELIX<<"GAGAGCGGGCGGGCGGGCGGCACAAGCGCGCGACAAAGTGCGTGGGCAGAGAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGCACAAATGCACGTGTGCGCGCGCGCGCGACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGCACAGGTAAATAGATAAACAACGGGAGAGCGGGCGGGCGGGCGGCACA\n";GCAT();
HELIX<<"GGTAAATACGCGCGCGACGGGAGAGCGGGCGGGCGGGCGGCACAGGTAAATACGTG\n";GCAT();
HELIX<<"CGTGACGGGAGAGCGGGCGGGCGGGCGGCACAAATAAACAACGGGAGAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGCACAAATATATGAGCAAGTGACGGGAGAGCGGGCGGGCGGGCGGCACA\n";GCAT();
HELIX<<"TATGAGCGCGCGCGCGACGGGAGAGCGGGCGGGCGGGCGGCACACACATATGAGCG\n";GCAT();
HELIX<<"CGCGACGGGAGAGCGGGCGGGCGGGCGGCACACACACACACACATATGAGCGCGCG\n";GCAT();
HELIX<<"ACGGGAGAGCGGGCGGGCGGGCGGCACACACACACACACACACATATGAGCGCGCG\n";GCAT();
HELIX<<"ACGGGAGAGAGAGCGGGTGAATAAGAGAGAGAGAGAAGGAACTAACCGATCAACTG\n";GCAT();
HELIX<<"GTAAATCGGCTAATTATTCGACTGGCGAACGATTGAGAGAAGGAGAGAAGGAGAGA\n";GCAT();
HELIX<<"AGGACTCGACTGCCTGTCTGCTCGGTTAGCGGCCAGCTGGCCGGACAACCAGCTGG\n";GCAT();
HELIX<<"CCGGTTGAGAGATCTAGAGAGAGAGAGAGAGAGAGAGAGACTTGATTAACCAGCTG\n";GCAT();
HELIX<<"GCGGACTGGTTAATCGAATGAACGAGCGCGTGCCGGTTAGGCGAATTAGTTGTTCG\n";GCAT();
HELIX<<"CCTGCTCGACTGACCGACTAGCGGGTAGACTGGTTAATCGATTAGCTGACTGGCTG\n";GCAT();
HELIX<<"GCAAGCGGACCAGTTACCTGGCGGACTGACTAGTCGCTCGTCCAATTAGATATCTG\n";GCAT();
HELIX<<"ACTAGCAAGCGGTTCGCCTGCTCGACCAGTTAATTGGCGGTTCGATTATCTGCTCG\n";GCAT();
HELIX<<"ATCGACTGACGAGAGATTCAGAGAATAAATAAAGGATTCGCCTGCTCGACCAGTTA\n";GCAT();
HELIX<<"ATTGGCGGTTCGATTATCTGCTCGATCGACTGGCAAGCGGATTAGTCGGTCAACTG\n";GCAT();
HELIX<<"ATCGCCTGGCGGTCAAGCGGGTGGGTGGTTGAGAGAGAGAAGGAATCGATTAGTTA\n";GCAT();
HELIX<<"TTCGCCTGGCGGACCAGTTACCTGGCGGAGTAAGCGCGCATATACGCGCACGAGCA\n";GCAT();
HELIX<<"GATACGTGAGTGGGTGGCGGTCAAGCGGTCGGCCAGTTGAGAGAGAGAAGGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGACCAGTTAGCTGACTGCCCAGCGGTCAAGCGGTCGGGCAAGCGG\n";GCAT();
HELIX<<"CCCGCTCGACCAGTTACCTGACTGGCTGGCGGTCAAGCGGCCGGTTGAGAGAAGGA\n";GCAT();
HELIX<<"ATCGGCCAACCGCTCGGCGGGTTAATTATTTGTTGAGAGAGAGAGAGAATAAATAA\n";GCAT();
HELIX<<"AGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGGGTGGAGTGGATACGTGAGTG\n";GCAT();
HELIX<<"CACGGCGGTACGAATATGTGCACGAACGAGTGGCGGAACGAATAGGTGAGTGGCGG\n";GCAT();
HELIX<<"GATGAGCAGGTAAGTGGCGGGATAAGCGAGTAAGTGGCGGGATGAATACACGGCGG\n";GCAT();
HELIX<<"AGTGAGTAGACGCACGTGCAAATAGCGGGTGGGCGGCCAACCAAGCGGTTCGACTG\n";GCAT();
HELIX<<"CCTGTTTGGCGACTGGACGAGCGGCCAACCAAGCGGTTCGACTGCCTGGTTGACCA\n";GCAT();
HELIX<<"GCTAGCTAGCGAATAGCCGGATAGACGAGCGGCCAACCAAGCGGACTGACTAGTCG\n";GCAT();
HELIX<<"CTCGTCCAATTAGATATCTGACTAGCGGCCAACCAAGCGGGTGGCTAAGCGGGCGG\n";GCAT();
HELIX<<"GTGGTTGAGAGAATAAATAAAGGAATCGACCAGTTAGCGGCTAACTAAGCGGTTCG\n";GCAT();
HELIX<<"ATTATCTGCTCGATCGACTGTTGAGAGAAGGAACCAGTTGTTCGCCTGCTCGACTG\n";GCAT();
HELIX<<"ACCGACTAGCGGGCTGTCTGACTAACTATCCAGCGATTCGATTATCTGCTCGATCG\n";GCAT();
HELIX<<"ACTGGTAAATCGTATATTCGCCTGCTCGGCGAACGAACGATTGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"AGGAACTGGTTAATCGATTAGCTGACTGGCTGGCGGCCAACCAAGCGGGTGGGGCA\n";GCAT();
HELIX<<"AGTGGGTAAGCACGCACCAACCAACGTAGTGGGTGGTTGAGAGAGAGAGAGAAGGA\n";GCAT();
HELIX<<"TTTGGCCAACCAGCTAACTGGCGGGCGAGCTGTCTGACTAACTATCCAGTAAATTG\n";GCAT();
HELIX<<"ACTGCCTGGCGAGTTAATTATTTGACGAACGAGAGAAGGATTCAGAGAAGGAAGGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAATCGGCCAACCGCTCGGCGGGCTAACTGCCTGCCTGACTGCTCG\n";GCAT();
HELIX<<"TTGAGAGAAGGAAGGAGAGAAGGAAGGATTCAGAGAAGGAAGGAGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGATTCGCCTGCTCGACCAGTTAATTGGCGGGTCGACCAGTTAACCGCTCGTCCA\n";GCAT();
HELIX<<"GCGGTCAAGCGGGTCGACCACCTGTTCGACTGCCTGCCAACCGACTAAGCGGGCGA\n";GCAT();
HELIX<<"GTTAATTATTTGACGAGTAACCTGATTATATATTCGCCTGCTCGACCAGTTAATTG\n";GCAT();
HELIX<<"GCGAACGATTGAGCGGGCGGGCGGGCGGATAAATAAGCGGCCTGATTAGCGGGTCG\n";GCAT();
HELIX<<"ACCAGTTAACCGCTCGTCCAGAGAAGGAGAGAAGGAAGGAAGGAGTTGATTACTCG\n";GCAT();
HELIX<<"GCGGGCGAACCAGTTACCTGGCGGGCTAATTATTTGGCGGTCAAGCGGTTGGTTGA\n";GCAT();
HELIX<<"GCGGGCTAATTATTTGGCGGCTAATCAAGCGGCCGGTTGAGCGGGCTAATTATTTG\n";GCAT();
HELIX<<"ACAAACAAACGAGAGAAGGAAGGAAGGATTCAGAGAAGGAAGGAAGGAAGGAACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGGCCAACCAATTGGCCAGCGGTCAAGCGGGCTAATTATTTGGCGG\n";GCAT();
HELIX<<"ATGAGCGGCCAGTTGAGAGAAGGAAGGAAGGAGAGAAGGAAGGAAGGAAGGATTCG\n";GCAT();
HELIX<<"TTTGACCACCTGATCGGCCAGCGGGCGAGTCGACCAGTTAACCGCTCGTCCATACA\n";GCAT();
HELIX<<"GCCAACCAATTGGCCATGTAACGAGAGAAGGAAGGAAGGAAGGATTCAGAGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAATCGACCGTTCGACTGGCGGATAGCCGGATAGCTGAAGGA\n";GCAT();
HELIX<<"TTCGTTTGACCACCTGATCGGCCAGCGGGCGAGTCGACCAGTTAACCGCTCGTCCA\n";GCAT();
HELIX<<"TACAGCTAATTATTTGTGTAACGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGATTCAGAGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAATCG\n";GCAT();
HELIX<<"ACCGTTCGACTGGCGGATAGCCGGATAGCTGAAGGAGCTAACTGCCTGCCTGACTG\n";GCAT();
HELIX<<"CTCGGCGGTCAAGCGGATAGAATGATAGTTGAGAGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGAAGGAAGGAGTCGCTCGACTGACCGATCATTGAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAATCGACCGTTCGACTGGCGG\n";GCAT();
HELIX<<"ATAGTCGGATAGCTGAAGGAGCTAACTGCCTGCCTGACTGCTCGGCGGTCAAGCGG\n";GCAT();
HELIX<<"ATAGAACGATAGTTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAGTCGCTCGACTGACCGATCATTGAGAGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGATCTAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"GTCGCTCGACTGACCGATCATTGAAGGAAGGAAGGAAGGAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAATCGACCGTTCGACTGGCGGATAGTCGGATAGCTGAAGGATTCGTTTG\n";GCAT();
HELIX<<"ACCACCTGATCGGCCAGCGGGCGAGTCGACCAGTTAACCGCTCGTCCATACAGCTA\n";GCAT();
HELIX<<"ATTATTTGTGTAACGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGATTCA\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAATCGACCGTTCGACTG\n";GCAT();
HELIX<<"GCGGATAGCCGGATAGCTGAAGGAGCTAACTGCCTGCCTGACTGCTCGGCGGTCAA\n";GCAT();
HELIX<<"GCGGATAGAGCGATAGTTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAGTCGCTCGACTGACCGATCATTGAGAGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGAAGGAAGGAATCGACCGTTCGACTGGCGGATAGTCGGATAG\n";GCAT();
HELIX<<"CTGAAGGAGCTAACTGCCTGCCTGACTGCTCGGCGGTCAAGCGGATAGCGTGATAG\n";GCAT();
HELIX<<"TTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"GTCGCTCGACTGACCGATCATTGAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGA\n";GCAT();
HELIX<<"AGGATCTAGAGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAGTCGCTCGACTG\n";GCAT();
HELIX<<"ACCGATCATTGAGAGAAGGAAGGAAGGAAGGATCTAGAGAAGGAAGGAAGGAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAACTGGTTAATCGATTAGCTGACTGGCTGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GCTAACTGCCTGCCTGACTGCTCGTTGAAGGAGAGAAGGAAGGAAGGATCTAGAGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAAGGATCTAGAGAGAGAAGGAAGGAGAGAAGGAAGGACCCGCTCG\n";GCAT();
HELIX<<"ACCAGTTACCTGACTGGCTGATGAATGATTGAGAGAGAGAAGGAAGGAACCAGTTG\n";GCAT();
HELIX<<"GCGGGCGACCCGCTCGACCAGTTACCTGACTGGCTGTCAATCAAAGTAAGCGCGCA\n";GCAT();
HELIX<<"TATACGCGCACGAGCAGATACGTGAGTGGGTGACGAGAGAAGGAAGGATTCAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAACTGGTTAATCGATTAGCTGACTGGCTGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGCGTACGTAGTTACGTAGTGGTTGAAATGAACGAGCGCGTGGCGAACGATTGA\n";GCAT();
HELIX<<"CGTAGTTAGGCAAGTGGGTAAGCACGCACCAACCAACGTAGTGGGTGGTTGAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGACCCGCTCGACCAGTTACCTGACTGGCTGGCGGTCAAGCGGCCGG\n";GCAT();
HELIX<<"TTGAGAGAAGGAAGGATCTAGAGAGAGAGAGAAGGATCTAGAGAAGGAACTGGTTA\n";GCAT();
HELIX<<"ATCGATTAGCTGACTGGCTGGCGGCCAACCAAGCGGGTGGCGTAGTGGTTGAAATG\n";GCAT();
HELIX<<"AACGAGCGCGTGGCGAACGATTGAGGCAAGTGGGTAAGCACGCAGTAAATCGGCTA\n";GCAT();
HELIX<<"ATTATTCGACTGGCGAACGATTGATCTAGTGGTTGAGAGAGAGAGAGAAGGAGCTG\n";GCAT();
HELIX<<"TCTGACTAACTATCCAGTAAATCGGCTAATTATTCGACTGGCGAACGATTGAGAGA\n";GCAT();
HELIX<<"TCTAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGAGACTTGATTAACCAGCTGGCGG\n";GCAT();
HELIX<<"GTCGATTAATTACCTGTTCGCCTGCTCGACCGCCCGTATACCGGTCGGGCGAATTA\n";GCAT();
HELIX<<"GTTGTTCGCCTGCTCGACTGACCGACTAGCGGGTAGACTAACCGATCAACTGGCAA\n";GCAT();
HELIX<<"GCGGTTCGCCTGCTCGACCAGTTAATTGGCGGACCGTCTGCCTGATTAACTAACCG\n";GCAT();
HELIX<<"CCTGACCAATCGACGAGAGATTCAGAGAGAGAAGGATTCGCCTGCTCGACCAGTTA\n";GCAT();
HELIX<<"ATTGGCGGCCTGACTGATCGGCCAGTTAACCAATCGACCAACCGGTTAGCAAGCGG\n";GCAT();
HELIX<<"ACCGTCTGCCTGGCCAATTACTCGACCACTCAACCGCCTGACCAATTAGTTAGCAA\n";GCAT();
HELIX<<"GCGGATTGACTGTTCGCCTGACCGCCTGACCAATTAGTTAGCAAGCGGTTCGACTG\n";GCAT();
HELIX<<"TCCGTCTGACTGGTTAATCGACTGTTGAGAGAGAGAGAGAAGGAACTAACCGATCA\n";GCAT();
HELIX<<"ACTGGCGGGCGGGCGGGCGGCCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGAATAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"AATAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGCCTAGCGGTACGTGTGAGTAGATAAGTGCACGAGCGCGTGAATACACG\n";GCAT();
HELIX<<"GCGGCACGAGTGCATGCCGGTCGAGCGGGATATGTGCACGTACGAGTGCACGTGCA\n";GCAT();
HELIX<<"GCGGCCTAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAA\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGAATAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAA\n";GCAT();
HELIX<<"ACAAACAAAATAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAA\n";GCAT();
HELIX<<"ATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTATTGAGAGAGAGAGAGAAGGAACCAGTTGGCGG\n";GCAT();
HELIX<<"GCGAACCGTCTGCCTGATTAACTAACCGCCTGACCAATCGGCGGACGGTCAAGCGG\n";GCAT();
HELIX<<"GTGGGTGGACGAGAGAAGGATTCAGAGAAGGAAGGAACTAACCGATCAACTGAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGCCAAAGCGTGTGCGTGAATA\n";GCAT();
HELIX<<"AGTAAGCGCGTGAGCAAACGGCGGAGTAAGCGGATAAGCAGATGAGTGTACGCGTG\n";GCAT();
HELIX<<"AGCGCGTGAGCAAATAGATAGCGGAGCATACGGCGGAGTGGATAAGCGGACGGGTA\n";GCAT();
HELIX<<"AGTGGGTGCTAAGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGAAGGAAGGACCAACCAAGCGGGTGGATAAATAAGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGACTG\n";GCAT();
HELIX<<"GTTAGCTGGCTATTGAGAGAAGGATCTAGAGAGAGAGAGAAGGAATCGATTATCTG\n";GCAT();
HELIX<<"CCTGGCGGCCAACCAAGCGGGTGGCGTAGTTAAGTGGATACGTGAGTGCACGGCGG\n";GCAT();
HELIX<<"CGTGAGTGAACGGGCAGATAAGCAAACGAGCAAGCGGATACTAAGCGGGCGGGTGG\n";GCAT();
HELIX<<"TTGAGAGAAGGAATTGACTGCCTGGCTAACCAGTTAACTGGCGAATCGACCAGTTA\n";GCAT();
HELIX<<"GCAAGCGGCCTGACTGATCGGCCAGTTAACCAATCGACCAACCGGTTAACGATTGA\n";GCAT();
HELIX<<"GAGAAGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGATAAATAAGCGG\n";GCAT();
HELIX<<"CCAACGTGAGTGAACGGGCAGATAAGCAAACGAGCAAGCGGATATCAACTAAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGCCTGACTGATCGGCCAGTTA\n";GCAT();
HELIX<<"ACCAATCGACCAACCGGTTAGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGA\n";GCAT();
HELIX<<"GAGAAGGAGAGAAGGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGAGTGGATACGTGAGTGCACGGCGGAGCGTGTGCGTGGGCAAATACACGAGCA\n";GCAT();
HELIX<<"CACAAGCGCGTGAGCAAATAGATACTAAGCGGGCGGGTGGTTGAGAGAAGGAATTG\n";GCAT();
HELIX<<"ACTGCCTGGCTAACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGACCGTCTG\n";GCAT();
HELIX<<"CCTGGCCAATTACTCGACCACTCAACCGCCTGACCAATTAGTTAACGATTGAGAGA\n";GCAT();
HELIX<<"AGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGATAAATAAGCGGCCAA\n";GCAT();
HELIX<<"AGCGTGTGCGTGGGCAAATACACGAGCACACAAGCGCGTGAGCAAATAGATATCAA\n";GCAT();
HELIX<<"CTAAGCGGGCGGGTGGGCGGCCAACCAAGCGGACCGTCTGCCTGGCCAATTACTCG\n";GCAT();
HELIX<<"ACCACTCAACCGCCTGACCAATTAGTTAGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTATTGAGAGAAGGAGAGAAGGAGAGAAGGAATCGATTATCTGCCTGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGGTGGAGTGGATACGTGAGTGCACGGCGGAATGAGTGTACGCGTGAGCG\n";GCAT();
HELIX<<"CGTGAGCAAATAGATACTAAGCGGGCGGGTGGTTGAGAGAAGGAATTGACTGCCTG\n";GCAT();
HELIX<<"GCTAACCAGTTAACTGGCGAATCGACCAGTTAGCAAGCGGATTGACTGTTCGCCTG\n";GCAT();
HELIX<<"ACCGCCTGACCAATTAGTTAACGATTGAGAGAAGGAACTAACCGATCAACTGGCGG\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGATAAATAAGCGGCCAAAATGAGTGTACGCGTGAGCGCGTG\n";GCAT();
HELIX<<"AGCAAATAGATATCAACTAAGCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGATTGACTGTTCGCCTGACCGCCTGACCAATTAGTTAGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTATTGAGAGAAGGAGAGAAGGAGAGAAGGAATCGATTA\n";GCAT();
HELIX<<"TCTGCCTGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGAGAGAAGGAGAGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAGCTGATTAGAGAAGGATTCAGAGAAGGAAGGAATCGATTATCTG\n";GCAT();
HELIX<<"CCTGGCGGCCAACCAAGCGGGTGGAGTGGATACGTGAGTGCACGGCGGTACGAGTG\n";GCAT();
HELIX<<"TGCGTGTGAGTGGATAAACGAGTGGCGGTACACGCGCACGAGTGTACGTACGGCGG\n";GCAT();
HELIX<<"AGTGGATACGTGAGTGCACGGCGGCGTGAATAGCGGTACGCGTGAATACGCGTGTA\n";GCAT();
HELIX<<"CTAAGCGGGCGGGTGGTTGAGAGAAGGAAGGAATTGACTGCCTGGCTAACCAGTTA\n";GCAT();
HELIX<<"ACTGGCGAATCGACCAGTTAGCAAGCGGTTCGACTGTCCGTCTGACTGGTTAATCG\n";GCAT();
HELIX<<"ACTGACGATTGAGAGAAGGAAGGAGAGAAGGAAGGAACCAGTTGGCGGGCGATTCG\n";GCAT();
HELIX<<"ACTGTCCGTCTGACTGGTTAATCGACTGGCGGACGGTCAAGCGGGTGGGTGGACGA\n";GCAT();
HELIX<<"GAGAAGGAAGGAAGGAACTAACCGATCAACTGGCGGCCAACCAAGCGGGTGGATAA\n";GCAT();
HELIX<<"ATAAGCGGCCAATACGAGTGTGCGTGTGAGTGGATAAACGAGTGTCAACTAAGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGTTCGACTGTCCG\n";GCAT();
HELIX<<"TCTGACTGGTTAATCGACTGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTATTGA\n";GCAT();
HELIX<<"AGGAGAGAAGGAAGGAGAGAAGGATCTAGCGGTTTGGCCAACCAGCTAACTGGCGG\n";GCAT();
HELIX<<"GCGATTCGACTGTCCGTCTGACTGGTTAATCGACTGGCGGACGGTCAAGCGGGTGG\n";GCAT();
HELIX<<"GTGGACGATTGAGAGAGAGAGAGAGAGATCTAGAGAGAGAGAGAGAGAGAGAGAGA\n";GCAT();
HELIX<<"GAGACTTGATTAACCAGCTGGCGGGTCGATTAATTACCTGTTCGCCTGCTCGACCG\n";GCAT();
HELIX<<"CCCGTATACCGGCTGGGCGAATTAGTTGTTCGCCTGCTCGACTGACCGACTAGCGG\n";GCAT();
HELIX<<"GTAGACTAACCGATCAACTGGCAAGCGGACCAGTTACCTGGCGGGTTATCTGACTA\n";GCAT();
HELIX<<"AGTGACTAGTCGCTCGTCCAATTATTCGACGAGAGATTCAGAGAAGGAACTAACCG\n";GCAT();
HELIX<<"ATCAACTGGCGGCCAACCAAGCGGGTGGATAAATAAGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGGGCGG\n";GCAT();
HELIX<<"GCGGGCGGGCGGGCGGGCGGGTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTA\n";GCAT();
HELIX<<"GTTACGTAGTTACGTAGTTAGTGGGAGAGAGAAGGAAGGACCAACCAAGCGGGTGG\n";GCAT();
HELIX<<"ATGGACCAGTTAATCGGCTATCTGGCTGACTGGCGGCCAAACCAATTATTCGCCTG\n";GCAT();
HELIX<<"CTCGACTGACCGACTACTAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGGTGGATGGACCAGTTAATCGGCTATCTGGCTG\n";GCAT();
HELIX<<"ACTGGCGGCCAATTCGCCTGCTCGACCAGTTAATTGCTAAGTGGGCGGCCAACCAA\n";GCAT();
HELIX<<"GCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGATGGACCA\n";GCAT();
HELIX<<"GTTAATCGGCTATCTGGCTGACTGGCGGCCAAGTTGTTCGCCTGCTCGACTGACCG\n";GCAT();
HELIX<<"ACTACTAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGATGGACCAGTTAATCGGCTATCTGGCTGACTGGCGGCCAA\n";GCAT();
HELIX<<"ATCGACTAACCGCCTGGCCACTAAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTG\n";GCAT();
HELIX<<"GCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTGTTCGACCAGTTAATTGGCGG\n";GCAT();
HELIX<<"TTCGCCTGGCTGCTGACTGAATCGACCAGTTATTGAGTGGGCGGCCAACCAAGCGG\n";GCAT();
HELIX<<"ACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTGTTCGACCA\n";GCAT();
HELIX<<"GTTAATTGGCGGTTCGCCTGGCTGCTGACTGAATCGATTATCTGCCTGTTGAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGTCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGAACTGGTTA\n";GCAT();
HELIX<<"GCTGGCTATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGA\n";GCAT();
HELIX<<"AGGACCAACCAAGCGGGTGGTCTGTTCGACCAGTTAATTGGCGGTTCGCCTGGCTG\n";GCAT();
HELIX<<"CTGACTGAACCAGTTGTTCGCCTGCTCGACTGACCGACTATTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTG\n";GCAT();
HELIX<<"TTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGAATTAGTTGTTCGCCTG\n";GCAT();
HELIX<<"CTCGACTGACCGACTATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGGTGGTCTGTTCGACCAGTTAATTGGCGGTTCG\n";GCAT();
HELIX<<"CCTGGCTGCTGACTGATTCGCCTGCTCGACCAGTTAATTGTTGAGTGGGCGGCCAA\n";GCAT();
HELIX<<"CCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGGGTGGTCTG\n";GCAT();
HELIX<<"TTCGACCAGTTAATTGGCGGTTCGCCTGGCTGCTGACTGACCCGATTATTTGTTGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTACGTAGTTAGTGGGAGA\n";GCAT();
HELIX<<"GAGAAGGAAGGACCAACCAAGCGGGTGGATCGATTAGTTATTCGCCTGGCGGACCA\n";GCAT();
HELIX<<"GTTACCTGGCGGAGTGAGTAGACGCACGTGCAAATATACGGCGGTCAAGCGGGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTTATCTGACTAAGTGACTAGTCGCTCGTCCAATTATTCG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGGTGGTTGAGTGGGCGGCCAACCAAGCGGGTGGCGTAGTTA\n";GCAT();
HELIX<<"CGTAGTTACGTAGTTAGTGGGAGAGAGAAGGAAGGACCAACCAAGCGGGTGGTTCG\n";GCAT();
HELIX<<"CCTGCTCGTCTGATCGCCTGGCGGGATATGTGCACGTACGAGTGCACGTGCAGTGG\n";GCAT();
HELIX<<"GCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAAGCGG\n";GCAT();
HELIX<<"GTGGTTCAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGATTCGCCTGCTCGACCAGTTAATTGGCGGAGCAGGTG\n";GCAT();
HELIX<<"TTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGCGGGAGAAGGAAGGA\n";GCAT();
HELIX<<"CCAACCAAGCGGGTGGAGGATTCGCCTGCTCGACCAGTTAATTGGCGGGGCAAGTG\n";GCAT();
HELIX<<"GGTAAGCACGCATTGAGTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGA\n";GCAT();
HELIX<<"AGGAAGGACCAACCAAGCGGGTGGAGGATTCGCCTGCTCGACCAGTTAATTGGCGG\n";GCAT();
HELIX<<"AGTAAGCGGATAAGCAGATGAGTGTACGCGTGAGCGCGTGAGCAAATAGATATTGA\n";GCAT();
HELIX<<"GTGGGCGGCCAACCAAGCGGACTGGTTAGCTGGCTAGAGAAGGAAGGACCAACCAA\n";GCAT();
HELIX<<"GCGGGTGGTCTATTGAGTGGGCGGCCAACCAAGCGGGTGGCGTAGTTACGTAGTTA\n";GCAT();
HELIX<<"CGTAGTTAGTGGTTGAGAGATCTAGAGA";GCAT();HELIX.close();}
void GCAT(){cout<<char('('+'*'+'*'+'*'-'+'-'+'+'-'+'-'-'/'-'/'-')');}
void HARVEST_EMBRYO(NURSERY EMBRYO){int zap='('+'-'-'*'+'-'-'+'-'*'-'+'+')';
ifstream YOU_ARE_NOT_AUTHORIZED_TO_READ_THIS(EMBRYO.HELIX.c_str());
ofstream YOU_MUST_IMMEDIATELY_DESIST(EMBRYO.MANIFESTATION.c_str());int bam=
'('-'+'-'+'-'+'+'/'+')'-'('+'+'+'+'+'+'-'/'-')';bool bang=bam;do{int
crunch;string zowie;getline(YOU_ARE_NOT_AUTHORIZED_TO_READ_THIS,zowie);
if(YOU_ARE_NOT_AUTHORIZED_TO_READ_THIS.fail())bang=zap;crunch=bam;int
klonk='('-'+'+'-'-'*'+')'-'('-'+'+'-'-'*'+')';int whap=klonk+zap;int
klunk='('-'+'-'*'+')'-'('-'+'+'/'+')'-'('+'/'-'*'+')';int zam=
klonk*klonk+klunk*klunk+klonk*klunk;int zamm=zam-klonk;int zammm=
klonk*klunk*klonk*whap;while(crunch<zowie.length()){int kerplop=bam;
for(int whack=whap;whack>=bam;whack--){char kapow=zowie[crunch];
int thwack=klonk+whack+klonk;kerplop+=(kapow==zam?pow(klonk,klunk-whack):
(kapow==zamm?pow(klonk,klunk-thwack):(kapow==zammm?pow(klonk,klunk-thwack)+
pow(klonk,klunk-whack):bam)));crunch++;GCAT();}YOU_MUST_IMMEDIATELY_DESIST<<
char(kerplop);}}while(!bang);YOU_ARE_NOT_AUTHORIZED_TO_READ_THIS.close();
YOU_MUST_IMMEDIATELY_DESIST.close();}
